### ISSUE TITLE
Silk on a Dragon Head on End Ship gave Skull instead

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#102]
Silk Touch Pick on Dragon Head on the front of the End Ship returned a #397/0 regular Skull Item.

**Comment by md-5** [comment]
Check vanilla for this one

**Comment by ghost** [comment]
Not a vanilla bug: https://gyazo.com/5f5a5643b91017de4dcdc32d4de05233

**Comment by klugemonkey** [comment]
Tested with 16w04a single player vanilla, Dragon head from end ship drops properly with silk touch pick in survival mode.

**Comment by md-5** [comment]
Fixed in 16w06a.
