### ISSUE TITLE
Default Wooden Shovel item for GriefPrevention claiming also creates path

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#107]
The default item for claiming an area with GriefPrevention is set to a Wooden Shovel.  In 1.9 the default right click action on a shovel will also clear a path on grass, changing the block metadata.  If a shovel is to be used as the item for selection of an area, it's default behavior should be disabled.
GP should handle the use item event on that block and return that the event has been handled.

**Comment by RoboMWM** [comment]
Already a known issue, and the author of GP is aware of this. He will cancel the event when 1.9 comes out.
