### ISSUE TITLE
Iron Golems are not Spawning 

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#108]
Village with 40 doors (birch) and 10 villagers does not spawn any iron golems.

**Comment by klugemonkey** [comment]
Manual spawning of iron golem with 4 iron blocks and a pumpkin works

**Comment by md-5** [comment]
Seeing this in the console:
`[19:52:50 INFO]: Not using : net.minecraft.server.VillageDoor@9a5b6f9`

``` java
                if (this.a.getType(blockposition1.shift(enumdirection, 1)).getBlock().b(this.a, blockposition1.shift(enumdirection, 1)) && this.a.getType(blockposition1.shift(enumdirection, -1)).getBlock().b(this.a, blockposition1.shift(enumdirection, -1)) && this.a.getType(blockposition1.up().shift(enumdirection, 1)).getBlock().b(this.a, blockposition1.up().shift(enumdirection, 1)) && this.a.getType(blockposition1.up().shift(enumdirection, -1)).getBlock().b(this.a, blockposition1.up().shift(enumdirection, -1))) {
                    villagedoor = villagedoor1;
                    i = j;
                    System.out.println("Using : " + villagedoor1);
                } else {
                    System.out.println("Not using : " + villagedoor1);
                }
```

Maybe your doors are not constructed correctly for 1.9?

**Comment by klugemonkey** [comment]
Sorry, gonna retest with default resource pack.

**Comment by klugemonkey** [comment]
Iron golems spawn on 1.9 vanilla with basic circular door design with villagers in center.

**Comment by klugemonkey** [comment]
I think this may be a 1.9 vanilla issue with villages not combining to create a larger village to spawn iron golems.

**Comment by klugemonkey** [comment]
When i put the villagers further than 16 blocks from each other, Iron Golems don't spawn, but village still combines according to village.dat with more than 10 villagers and 21+ doors.   Anyway, i think this is a vanilla behavior, not a Bukkit issue.

**Comment by klugemonkey** [comment]
Retesting with circular village in Spigot to confirm that golems do in fact spawn naturally.

**Comment by klugemonkey** [comment]
Circular village with 10+ villagers and 48 doors spawned an Iron Golem on Spigot.
