### ISSUE TITLE
Boats on Land - Disappear from Inventory

### ISSUE THREAD

**Issue by 2008Choco** [SpigotMC/SpigotCraft#109]
When right clicking on the ground with a boat, the boat will disappear from your inventory until you click on the inventory slot it was in with your mouse. (Client side glitch, though unaware of whether it's Spigot or Minecraft itself causing the issue).

In hand, about to place the boat:
![2016-02-18_18 30 33](https://cloud.githubusercontent.com/assets/10508906/13161747/caefecb4-d66d-11e5-9491-3d44a2ad64ef.png)

After attempting to place the boat (You can see it's placed, as the item cooldown is active beside my hotbar:
![2016-02-18_18 30 43](https://cloud.githubusercontent.com/assets/10508906/13161748/ccdd0bc4-d66d-11e5-923c-74042877e982.png)

Here's what happens when I click in the slot that the boat was in:
![2016-02-18_18 30 57](https://cloud.githubusercontent.com/assets/10508906/13161751/cf709aae-d66d-11e5-970d-d884ec689a74.png)

**Comment by md-5** [comment]
Cannot reproduce
