### ISSUE TITLE
Zombie Villager cured in cart drops out of cart 1 block below

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#111]

**Comment by klugemonkey** [comment]
A zombie villager cured in a minecart not on a rail was instantly turned into a villager and placed 1 block below the cart, not actually in the cart.  Cart could be moved afterwards and destroyed, but villager is stuck in the block below with head and arms above.

**Comment by md-5** [comment]
How do you cure a villager? Also check Vanilla multiplayer.

**Comment by klugemonkey** [comment]
curing a zombie villager with a splash potion of weakness and a golden apple.

**Comment by md-5** [comment]
Cannot reproduce
