### ISSUE TITLE
Implement Shops

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#112]
One good option:
http://dev.bukkit.org/bukkit-plugins/chestshop/

**Comment by saturnux** [comment]
chestshop is a good plugin, and it link directly with essentials. Or other with vault.

**Comment by Arektor** [comment]
:+1: May be cool for making public shops.

**Comment by 0x277F** [comment]
:+1:

**Comment by 2008Choco** [comment]
:+1:

**Comment by md-5** [comment]
ChestShop has been implemented
