### ISSUE TITLE
Crafting shields with banners doesn't work

### ISSUE THREAD

**Issue by Arektor** [SpigotMC/SpigotCraft#113]
Ok so, whenever I try to craft a shield, it works.
But when I try to apply a banner on it, it shall give me a normal shield in the output, and when I try to pick it up, the craft is cancelled.

When I'm lagging, I can see the shield with the banner for a moment, then it got replaced by a normal shield.

EDIT: I tried with damaged and non-damaged shields: Same issue.

**Comment by md-5** [comment]
Fixed internally.

**Comment by iPyronic** [comment]
This is still bugged. I can put a shield and banner together and the resulting shield looks like it should, but I can't actually take it. The crafting is cancelled and the item I receive is a fake that just disappears once updated.

Tested using a shield with low durability and a banner with 1 design on it.

**Comment by md-5** [comment]
Mhm, I've re-fixed it again for the next version
