### ISSUE TITLE
Unable to attach leash to fence post

### ISSUE THREAD

**Issue by iPyronic** [SpigotMC/SpigotCraft#120]
Animals can be put on a leash like normal, but when you try to attach the held leash to a fence it doesn't work. The animal becomes unleashed and the lead item drops on the ground. No sound is played either.

On a vanilla pre-release 3 server, the leash can be placed on a fence without a problem, and the first animal to be leashed to the post causes a sound to be played.

**Comment by md-5** [comment]
Resolved

**Comment by iPyronic** [comment]
Leashes still break and drop to the ground instead of attaching the mob to the fence.

I tested both inside and outside of my claimed land in case that had been the problem, but it was the same result.

**Comment by md-5** [comment]
Re-fixed
