### ISSUE TITLE
Entity damage doesn't appear to cancel properly?

### ISSUE THREAD

**Issue by Puremin0rez** [SpigotMC/SpigotCraft#122]
Currently using Minecraft 1.9 Pre 3

I am near spawn at LegitPlays base, where he keeps his animals in a fenced in pen.

I am able to attack the animals even though I am being told I cannot, however the animals appear to take no damage - yet they visibly show them taking damage and run around as if they were just hurt. I have tried multiple swords and fists and I am unable to kill these mobs, yet they still look as if they're being hit.

I think this issue has cropped up recently because I remember hopping on for 1.9 Pre 1 and this issue did not occur.

**Comment by md-5** [comment]
It's the fix for https://github.com/SpigotMC/SpigotCraft/issues/119
I'm at a loss as to how to solve this :\
Tempted to just bring 119 back as a regression
