### ISSUE TITLE
Zombie and Creeper - No Death Message

### ISSUE THREAD

**Issue by hook321** [SpigotMC/SpigotCraft#123]
I was near spawn, kinda low on health, then both a zombie and a creeper started to come towards me, I'm not sure which one killed me, but their wasn't any death message.

**Comment by md-5** [comment]
Did you die recently? One of the plugins on the server makes it do you only get a death message if you die more than a minute apart.

**Comment by hook321** [comment]
I have no way of knowing, I don't have that log anymore. I would assume that would be the issue... Does a plugin handle the death messages, or is it part of spigot? If they were in the same block at the time I died could that have resulted in their not being a death message?

**Comment by md-5** [comment]
Well I checked creepers and they worked fine. Zombies do also. I'm gonna assume this was the GriefPrevention cooldown.

**Comment by md-5** [comment]
(https://github.com/SpigotMC/SpigotCraft/blob/master/plugins/GriefPreventionData/config.yml#L56)

**Comment by hook321** [comment]
Huh. Never knew there was an option for that. I'll have to try using it.

**Comment by md-5** [comment]
It's a plugin option that we use on the server
