### ISSUE TITLE
Adding GriefPrevention

### ISSUE THREAD

**Issue by ctian1** [SpigotMC/SpigotCraft#13]
We should use GriefPrevention alongside WorldGuard and LogBlock since it allows players to claim land themselves among many other great features.

**Comment by JamieSinn** [comment]
Could be interesting, if used for only claiming land, then we need a different plugin, not GP.

**Comment by RoboMWM** [comment]
PR #23 
Feedback is welcome.

**Comment by jeff142** [comment]
:-1:

Honestly hate this plugin, its anoying imo

**Comment by RoboMWM** [comment]
What's annoying about it? Disabled land claiming features if that's what you're talking about.

**Comment by jeff142** [comment]
whats the point of it if you disable land claiming?

**Comment by RoboMWM** [comment]
See PR description. More effective antispam, additional PvP-like protection in non-PvP worlds such as lava/flint and steel and pet/horse protections.

**Comment by Cldfire** [comment]
:-1: Griefprevention isn't a very good claim plugin.

This should be used https://www.spigotmc.org/resources/districts.989/

**Comment by JamieSinn** [comment]
Districts looks immensely better for claiming :+1: for districts.

**Comment by RoboMWM** [comment]
I fail to see how GriefPrevention "isn't a very good claim plugin" other than not having a chest gui for micromanaging claims, unless I guess if you want to buy and sell entire claims...
