### ISSUE TITLE
Rename plugins to contain version

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/SpigotCraft#131]
Something like plugin-1.1.1.jar to be able to know which version the server is running, which features it offers and which plugins may need to be updated. 
I would pr this if I would know the version...

**Comment by RoboMWM** [comment]
```
[01:30:26] CafeBabe: [SpigotCraft] MiniDigger opened issue #131: Renamed plugins to contain version 
[02:01:24] RoboMWM: wat
[02:01:28] RoboMWM: that's a horrible idea
[02:01:41] RoboMWM: it's as easy as /version pluginname if you really want to find out
```

**Comment by MiniDigger** [comment]
still don't know why this is a horrible idea but I guess we can close this in favor of the /version command :D

**Comment by TomLewis** [comment]
@MiniDigger its a horrible idea, because then you cant use the ./update folder in plugins to update your plugins.

**Comment by RoboMWM** [comment]
```
[02:43:07] CafeBabe: [SpigotCraft] FrozenBeard commented on issue #131: @MiniDigger its a horrible idea, because then you cant use the ./update folder in plugins to update your plugins. 
[02:43:15] RoboMWM: eh it's just a ton harder to update imo, I like just draggin and droppin into the update folder, press restart, boom, ... oh hey look at that
```

**Comment by MiniDigger** [comment]
> I do it like that all the time because I like to have a clear look at what I am running. updating involves only one additional step and I don't use auto updaters

**Comment by TomLewis** [comment]
@RoboMWM That too! Drives me mad when plugins have version numbers. Im sure you can extract a plugin to find its version too? Maybe a better option would be having /plugins show version numbers, and have them in a proper list, hell Spigot could go a step further and check their resources for updates.

**Comment by MiniDigger** [comment]
that would actually be a cool idea for to implement into spigot, an automated update checker that uses the plugin.yml for information (and can be globally disabled in the spigot.yml) 
you could even go that far to have multiple "update sources", eg dbo, spigot, other places that are frequently used and offer a api. 
but guess md would save it fits better into a plugin ;)

**Comment by TomLewis** [comment]
Or a much simpler fix would be making each plugin name clickable in /plugins simply just run /version plugin name, That would be a very simple implementation using what we already have.

**Comment by electronicboy** [comment]
I really don't see the issues of the context of the updates folder in regards to this setup?
The whole intent that stuff can be thrown into the update folder doesn't really apply to this setup, so I don't see why that needs to be brought up in here.

Also, a plugin update checker would be something for a plugin to implement, Features like that just add extra work onto a bunch of devs who already have dozens of other stuff to work on.

**Comment by TomLewis** [comment]
@electronicboy plugin-name1.11.jar in plugins, you put in plugin-name1.1.2.jar intot he update folder, it does not work as its not the same name... that simple mate.

And no, adding a plugin check for the developer is always the worst way to do an update check IMO. I have had plugins decide to auto update themselves, why anyone would ever want this is beyond me, I assume very naive young server managers. 

Stop trailing off topic @electronicboy

**Comment by electronicboy** [comment]
How was I off-topic?

I was addressing @MiniDigger in regards to his update checker and supporting the fact it would be better as a plugin if one ever was created. I meant it in a generic 'one checks all' type of update checker that was reffered to, it would be better as a plugin instead of being directly integrated into the server.

And I know about the update folder, I use it myself; But you're acting like the update folder is actually applicable to the setup of this repo. MD most likely doesn't use the update folder to perform the updates to the server and most likely just performs a pull from the repo.

**Comment by TomLewis** [comment]
@electronicboy I thought you were replying to me as you never tagged the person you were talking to, So calm your passive aggressiveness and learn how to communicate on Github.

**Comment by electronicboy** [comment]
We're talking on github in reference to _this_ repo used by Spigot, I'm overly tired, but I don't see the issues with my initial reply if you actually follow the context of the discussion. I don't see where the ambiguity of my replies direction could actually have any effect on the discussion.

**Comment by TomLewis** [comment]
@electronicboy get some sleep man, I have no beef. We're all looking for improvements.
