### ISSUE TITLE
More Functional Testing Group

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#135]
We need to create a more functional Testing group for 1.11 - give, summon, gamemode etc.
Possibly an additional Helper group for users to be able to promote other trusted users.

**Comment by Z609** [comment]
:+1:

**Comment by ltcrazyman** [comment]
happy to help test where needed

**Comment by Dani9OO** [comment]
I would love to participate :)

**Comment by MiniDigger** [comment]
so you need ppl that test new (and probably the old too)  features to confirm that they are working? 
I would like to help out.
do you plan out setting up like a Google docs with everything that needs to tested or should everybody just test everything they can think of?

**Comment by MakerTim** [comment]
Im a redstone nerd,
Of you need tester's in the Redstone components to the limit, I'm here 0/

http://torontogaymers.ca/wordpress/wp-content/uploads/2014/05/hObIps2.jpg

**Comment by MiniDigger** [comment]
@md-5 I don't know if you still have the "Testing Ideas" list from the 1.8 testing (https://www.spigotmc.org/threads/1-8-testing-begins.34636/) but I think it would be a great idea so setup something like this again **and keep it for every new (major) release**, adding new stuff every time

**Comment by TimoZikeli** [comment]
me! :)

**Comment by Doc94** [comment]
+1,
test the basic systems events?

**Comment by x9nico** [comment]
me! :)

**Comment by WouterG** [comment]
also interrested

**Comment by JitseB** [comment]
interested as well ;3

**Comment by JamieSinn** [comment]
I'm game

**Comment by JoeyHaalboom** [comment]
I would love to help you out.
