### ISSUE TITLE
Add AsyncWorldEdit?

### ISSUE THREAD

**Issue by PatoTheBest** [SpigotMC/SpigotCraft#14]
https://www.spigotmc.org/resources/asyncworldedit.327/

**Comment by ctian1** [comment]
:+1: once plotworld is in

**Comment by ghost** [comment]
:-1: I don't see why asyncworldedit/worldedit should/would be needed on a plotworld.

**Comment by ctian1** [comment]
@Chnkr for players to build using?

**Comment by ghost** [comment]
@pangeacake allowing players to use those tools will allow them to grind the server to a halt, i don't see why that should be allowed.

**Comment by ctian1** [comment]
@Chnkr if it's limited correctly and only give to trusted players it should be fine..

**Comment by 0x277F** [comment]
I don't see why not, but I'd also say this would be lower-priority.

**Comment by JamieSinn** [comment]
@0x277F I'm with you on this, but for plot world, I see no need.
It's "Creative", not WorldEdit build what the heck you want that will crash the server

**Comment by ctian1** [comment]
@JamieSinn, why not give more powers to trusted players? Of course, WorldEdit for them will still be limited.. though it's still helpful for building

**Comment by JamieSinn** [comment]
@pangeacake World Edit is just something waiting to be abused.

**Comment by LaxWasHere** [comment]
:-1: There shouldn't be W/E.

**Comment by Techcable** [comment]
:+1: for adminss

**Comment by ctian1** [comment]
@JamieSinn, normal WorldEdit is already installed anyways

**Comment by JamieSinn** [comment]
@pangeacake I know, but for the plot world? Not needed.

**Comment by RoboMWM** [comment]
If WorldEdit is to be used more than as a dependency (it's needed for WorldGuard), then a :+1: for this or Fast Async WorldEdit https://www.spigotmc.org/resources/free-fast-async-worldedit-%CE%B2.13932/

**Comment by ghost** [comment]
:+1:

**Comment by jeff142** [comment]
:+1:

This plugin can save you from a doing 20 smaller edits and save you from crashing your server, defiantly would recommend

**Comment by Cldfire** [comment]
:+1:

**Comment by HappyHarm** [comment]
:+1: If there is a plotworld yes. Else you have to limit how many blocks someone can worldedit so this is a better alternative

**Comment by Nebhay** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by TitanicFreak** [comment]
:+1:

**Comment by ajthemacboy** [comment]
:+1:

**Comment by Zeryther** [comment]
:+1:

**Comment by Techcable** [comment]
@RoboMWM

**Comment by DoNotSpamPls** [comment]
:-1: md_5 himself said that WorldEdit would be only for staff usage
https://www.spigotmc.org/threads/an-idea.88964/

**Comment by ajthemacboy** [comment]
Staff wouldn't benefit from this..? It's not like AWE is just for players.
