### ISSUE TITLE
Inventory updates from manipulation don't always apply on the client

### ISSUE THREAD

**Issue by electronicboy** [SpigotMC/SpigotCraft#149]
Sometimes, when performing inventory manipulation, the item will be moved from its original location (e.g. an inventory, the cursor), however, the destination slot will not be updated.

**Comment by md-5** [comment]
Needs specific reproduction steps and vanilla cross checking.

**Comment by electronicboy** [comment]
I've been playing with a vanilla server, however not as intensive as the test server and have not been capable of reproducing this on vanilla, nor can I reliably reproduce this on the test server.

So far I've managed to replicate this while picking an item up with the cursor and dropping it into another location in an inventory, the client will acknowledge that the item is no longer on the cursor, however the slot the item was placed into wasn't actually updated to show it contained the item in that location.

I also managed to reproduce this by shift clicking an item in my inventory screen, the item would disappear from the original location however it wouldn't be seen in the new location until you interact with it.

Looking at it, Along with the other issue I asked about on IRC, I'm going close this issue under the doozy that it's most likely a latency issue, however I've never had issues like this on a bad connection, however, this is now 1.11, so a behavioural change might be tripping me up if it actually is latency.

**Comment by md-5** [comment]
Could also be NoCheat for all we know

**Comment by johnfriedrich** [comment]
Experienced the same, but cannot reproduce it. Maybe just too rnd.
Moved a 54 stack of wood from inventory with my cursor to the hotbar manually. Stack was gone. Needed to relogg to see it again.

**Comment by md-5** [comment]
Can reproduce
