### ISSUE TITLE
Signs appear blank

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#151]
By placing a sign and writing text on it, it will appear blank.

Example here: https://img.ssamjh.nz/i/bu6bp.gif

But someone elses signs are working?? https://img.ssamjh.nz/i/y0i1r.png

**Comment by TNTUP** [comment]
Confirming this issue aswell for me, I've found another workaround by renaming items xD

**Comment by md-5** [comment]
It's something to do with griefprevention. Gotta find out what and if it's our bug.

**Comment by md-5** [comment]
Actually struggling to reproduce this at all

**Comment by md-5** [comment]
Ok so we discovered it was the Nocheat+ autosign check.
I can't find any inconsistency on our end, so closing.
