### ISSUE TITLE
Hopper Server Crash

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#152]
Why the server is down now :)

**Comment by ssamjh** [comment]
Alright, thanks for the update! I was making a safe bridge for the end spawn :D

**Comment by TNTUP** [comment]
I thought it was caused due to someone trying to break a observer block in a protected claim. Are observers could make lag if left on (You were on my claim earlier)? Made it for redstone wire going up/down vertically as observers XD

**Comment by md-5** [comment]
Anyone particularly knowing what they were doing?

```
Block location: World: (-81,77,103), Chunk: (at 15,4,7 in -6,6; contains blocks -96,0,96 to -81,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
```

**Comment by ssamjh** [comment]
No sorry, I can't recall seeing hoppers anywhere.

**Comment by md-5** [comment]
Nevermind, appears just dropping an item in is enough to crash it

**Comment by IRTHATDUDE** [comment]
I dropped a shulker box on top of a hopper right before the server closed. I hope i didnt cause any issue

**Comment by ssamjh** [comment]
^^ That might have been it.

**Comment by md-5** [comment]
Nope, we're looking for issues exactly like this.
Fixed version is uploading now.

**Comment by IRTHATDUDE** [comment]
Phew, good to know I'm useful. I shall find them all...
