### ISSUE TITLE
End Portal Credit Glitches

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#157]
It appears that when some users go through the end portal in creative they don't see the credits and get stuck in a state of flux.
When they relog they get the credits.

Sam made a video here:
https://www.youtube.com/watch?v=HY-SUgokdiU

**Comment by ssamjh** [comment]
Cannot reproduce with a Vanilla client or server.
Only happens to some accounts and only on the Spigot test server.

**Comment by ssamjh** [comment]
Might be a NoCheatPlus issue. Needs more diagnosing.
