### ISSUE TITLE
Placing a shulker box in a claim causes it to drop itself (Effectively duplicating)

### ISSUE THREAD

**Issue by Yamakaja** [SpigotMC/SpigotCraft#158]
Creative mode:
Always just dupes the item

Survival mode:
Glitches the item in your hand out until you drop it and pick it back up

**Comment by Yamakaja** [comment]
Note: This doesn't apply to spawn protection. Probably a problem with the block-place event not being handled correctly

**Comment by md-5** [comment]
I've redone shulker dropping. I'd appreciate a good testing of anything to do with dropping a shulker block once the update is live.

**Comment by md-5** [comment]
Placing it in the protected area now creates a client side double in the inventory

**Comment by Yamakaja** [comment]
Placing shulker boxes in non-protected ares in survivalmode fails
