### ISSUE TITLE
Replace NoCheatPlus with a better alternative.

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#16]
NoCheatPlus has a lot of flaws, and does not stop most, if not all public and private 'hacks'

**Comment by JamieSinn** [comment]
Most better alternatives are paid. NCP blocks enough to be in a base server
:-1:

**Comment by Techcable** [comment]
:-1:

**Comment by RoboMWM** [comment]
Other than PvP-related checks, which doesn't matter, NCP should suffice.
:-1:

**Comment by jeff142** [comment]
I agree with the others 
:-1:

**Comment by ghost** [comment]
> Most better alternatives are paid. NCP blocks enough to be in a base server

Bypassing the default built-in NCP checks is fairly easy, that's why i'm suggesting we either use a alternative, or tweak the settings.

The following `checks` can easily be bypassed.
- All checks regarding flying.
- All checks regarding speed
- All checks regarding fastbreak
- All checks regarding jesus/walking on water.

**Comment by Sataniel98** [comment]
:-1:

**Comment by RoboMWM** [comment]
Afaik, the only checks I know that are bypassed is a "gliding" sort of flying (which may have already been patched, not sure), and perhaps the walking on water. As for the rest, I don't think that's the case. Would like more info on that..

**Comment by gardenerik** [comment]
:-1:

**Comment by MyPictures** [comment]
FastBreak I highly doubt is bypassed. Many claim to have a bypass for it because FastBreak check allows one cheated block per 20 block breaks (or so) to smooth out lag. You can disable that if you want to be strict.

As for SurvivalFly I do not know much since I have been out of the hacker scene for a while now. Im aware of jesus/dolphin whatever bypass. Glide has been fixed in the latest revision and a fly bypass I do not know of.

**Comment by AlexM850** [comment]
NoCheatPlus is definitely the best option. If configured correctly, you can easily block 99.9% of anything that you're having trouble with. You just have to spend time with configuring and tweaking it both for performance and to stop hacking.

**Comment by asofold** [comment]
I am not entirely sure which version of NCP would be the appropriate one to use, for starters :p. The config shows build 785 - which is almost 100 builds outdated by now (dev builds are at 874, latest "mostly stable" is at 853). The latter builds have a reflection based compat module for block shapes, which might or might not work, at least it can be deactivated. The latest builds (785...) should mostly kill off any abuse of vertical velocity (glide).

Unfortunately (?) i can't test stuff myself so i don't even know the item names... do you have the potion effect and elytra added to the Bukkit API part in use there?

**Comment by ghost** [comment]
I agree with the others as well, NCP does it's job. :-1:

**Comment by ghost** [comment]
:-1:

**Comment by DoNotSpamPls** [comment]
:-1:

**Comment by NahuLD** [comment]
:-1:

**Comment by ghost** [comment]
@NahuLD There is no reason to :-1: a issue that was opened back in 2015, as you can clearly see it was not utilized nor considered, so your :-1: means nothing.
