### ISSUE TITLE
Random nether portal selection

### ISSUE THREAD

**Issue by titivermeesch** [SpigotMC/SpigotCraft#166]
Found something interesting.
The nether portal don't generate in the nether, so 2 nether portals in the overworld that are really far away from each other teleport to one single portal in the nether.

PlayBossWar

**Comment by ScruffyRules** [comment]
How far away? I tested 5.5k away from spawn and it works.

**Comment by ploppyperson** [comment]
From my testing, if I make another nether portal further away, I get taken to the nether portal (in the nether) from the one at spawn. If I re-enter the portal in the nether, then I get taken back to the spawn one.

**Comment by titivermeesch** [comment]
Maybe I was too far away then.
