### ISSUE TITLE
No slime spawning in Swamp biomes

### ISSUE THREAD

**Issue by loetje165** [SpigotMC/SpigotCraft#168]
I have been searching and investigating a couple of swamp's but I have not seen a single slime yet.

**Comment by ssamjh** [comment]
From testing we seem to have found some slimes spawning, but it is a lot lower than usual (in the flat world we created).

**Comment by BillyGalbreath** [comment]
Slime spawning is hugely affected by the render distance. A slime will not spawn within 28 blocks of a player, and farther than 32 blocks the despawn. The test server seems to be set pretty low render distance, which would make slimes extremely rare.
