### ISSUE TITLE
Standing on top of an opening Shulker will close invenmtory

### ISSUE THREAD

**Issue by WolverinDEV** [SpigotMC/SpigotCraft#169]
I think th title says all.
If you standing on top and open a shulker than it would close.

Lg WolverinDEV

**Comment by ScruffyRules** [comment]
Can confirm, this **IS** a Spigot (And maybe CraftBukkit) bug.

**Comment by Yottazoid** [comment]
I found this earlier and was not able to reproduce in vanilla.
It will only close for the person standing on top.

**Comment by ScruffyRules** [comment]
Just for reference this is about a player moving, not directly related to shulker boxes.

**Comment by WolverinDEV** [comment]
Yes in vanilla it wouldn't close http://screencloud.net/v/pX3g

**Comment by Yottazoid** [comment]
I found the same thing happens if the player is pushed by a piston. It also happens with the inventory screen and chests.  It doesn't happen if the player jumps and opens the inventory at the same time though.

**Comment by MiniDigger** [comment]
have a nice gif (I need to justify wasting my time taking it before searching the issues...)
![http://i.minidigger.me/2016/11/2016-11-16_17-15-50.gif](http://i.minidigger.me/2016/11/2016-11-16_17-15-50.gif)
http://i.minidigger.me/2016/11/2016-11-16_17-15-50.gif

**Comment by BillyGalbreath** [comment]
This was hit or miss for me. The inventory would not close consistently, and sometimes remain open.

**Comment by electronicboy** [comment]
it opened once for me, and again it wouldn't. I would potentially attribute this to the cheat systems, the act of moving up could be considered jumping, while opening an inventory, something to take into consideration

**Comment by MiniDigger** [comment]
I can reproduce it on every attempt

**Comment by nayoshi** [comment]
It also works with every direction

**Comment by JamieSinn** [comment]
Cannot replicate if items are inside the box before standing on it.

**Comment by md-5** [comment]
This is a combination of a plugin and latency. Dunno which one but yeah
