### ISSUE TITLE
Vanilla or Modded Survival?

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#17]
Is this server intended to be ran as a purely vanilla server, or will there be slight modifications that allow for fun, and new interesting things?

**Comment by ctian1** [comment]
Well, there already are many server plugins, so..

**Comment by JamieSinn** [comment]
Vanilla. All we need.

**Comment by ghost** [comment]
@pangeacake The current set of plugins does not modify gameplay, it only allows for better moderation and administration, i'd made this issue to see if @md-5 was planning to turn this into a close-to-vanilla server, which only contains essential tweaks and changes, or into something else.
