### ISSUE TITLE
Placing hopper on top of a shulker dosnt work

### ISSUE THREAD

**Issue by WolverinDEV** [SpigotMC/SpigotCraft#170]
If you place a hopper over the shulker the hopper wound insert items.

Also playcing a block over a shulker and a hopper at one side would not work too :)

**Comment by ScruffyRules** [comment]
Works just fine here.

**Comment by WolverinDEV** [comment]
yeah i just saw my fail was that i put a shulker in the dropper. I tested in sp with an other item
