### ISSUE TITLE
Baby zombie hotbox is off

### ISSUE THREAD

**Issue by andrewfer000** [SpigotMC/SpigotCraft#179]
I don't know if its just me but i can hit baby zombies at normal zombie height and they are also much faster and stronger

**Comment by andrewfer000** [comment]
Hitbox*

**Comment by wyatt-herkamp** [comment]
I see it. http://imgur.com/a/Juc5q
It is too short.

**Comment by MiniDigger** [comment]
not a spigot issue, same for vanilla

**Comment by MiniDigger** [comment]
not a spigot issue, same for vanilla
vanilla left, spigot right
![http://i.minidigger.me/2016/11/javaw_16_17-25-29.png](http://i.minidigger.me/2016/11/javaw_16_17-25-29.png)
http://i.minidigger.me/2016/11/javaw_16_17-25-29.png
