### ISSUE TITLE
Add IRC integration

### ISSUE THREAD

**Issue by 0x277F** [SpigotMC/SpigotCraft#18]
... via some plugin such as https://www.spigotmc.org/resources/purpleirc.2836/. This would be linked to a new channel in the irc.spi.gt network that would be moderated by the existing IRC staff.

**Comment by JamieSinn** [comment]
:+1:

**Comment by ctian1** [comment]
Does this mean we'll be hosting an official SpigotCraft server?

**Comment by md-5** [comment]
Yeah I've already got it set up, really spammy if I included it whilst people ran test servers though.
