### ISSUE TITLE
trying to rename a item in anvil shows a firework at first

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/SpigotCraft#180]
![http://i.minidigger.me/2016/11/javaw_16_17-33-06.png](http://i.minidigger.me/2016/11/javaw_16_17-33-06.png)
http://i.minidigger.me/2016/11/javaw_16_17-33-06.png

vanilla behavior is to show no item at all

changing the name works tho
![http://i.minidigger.me/2016/11/javaw_16_17-35-18.png](http://i.minidigger.me/2016/11/javaw_16_17-35-18.png)
http://i.minidigger.me/2016/11/javaw_16_17-35-18.png
but leaves a firework behind
![http://i.minidigger.me/2016/11/javaw_16_17-35-42.png](http://i.minidigger.me/2016/11/javaw_16_17-35-42.png)
http://i.minidigger.me/2016/11/javaw_16_17-35-42.png
(non clickable)
gif showing everything
![http://i.minidigger.me/2016/11/2016-11-16_17-37-02.gif](http://i.minidigger.me/2016/11/2016-11-16_17-37-02.gif)
http://i.minidigger.me/2016/11/2016-11-16_17-37-02.gif

**Comment by amadeusmz** [comment]
Just put spawner eggs to 1st slot of anvil and it will give you firework
A minor harmless bug, since it's unclickable it maybe a vanilla issue.

**Comment by forseth11** [comment]
This bug occurs with diamond swords as well.  Actually every item in an anvil shows a firework at first.

**Comment by MiniDigger** [comment]
its not a vanilla issue.
i can confirm that it occurs for other items too tho

**Comment by electronicboy** [comment]
Tested between vanilla and spigot, vanilla handles without any issues, while Spigot will place a firework intermittently, seemingly on all interactions with the anvil there is probably about 50% chance that it will perform this.

modifying the contents of the name slot (However, once it's already got the correct item in there, I've not managed to cause it to trigger this bug).
Placing or removing an item from the 1st slot

**Comment by ploppyperson** [comment]
this also occurs with the second slot

**Comment by JamieSinn** [comment]
I mean, the firework id is 401. HTTP 401 is Unauthorized... coincidence?
:+1: 

Happens with invalid combos such as http://i.imgur.com/9F94Nsi.png instead of showing http://i.imgur.com/TqEsqbr.png

**Comment by md-5** [comment]
Can't reproduce, nothing changed so idk

**Comment by MiniDigger** [comment]
server restart seems to have fixed it
