### ISSUE TITLE
Shields drop

### ISSUE THREAD

**Issue by forseth11** [SpigotMC/SpigotCraft#183]
When hitting a person who is actively shielding with a sword or ax, the visual part of the shield drops to not shielding even when the player is still holding their shield up from their point of view.  This issue does not seem to occur for any other weapons.  This can be very crucial for pvp in minecraft.

**Comment by md-5** [comment]
Can someone please look at this further and compare with 1.10 spigot.

**Comment by ScruffyRules** [comment]
In 1.11 vanilla it doesn't drop the shield, tested with ssamjh.

**Comment by md-5** [comment]
And 1.10 spigot?
