### ISSUE TITLE
Issues with redstone, transparent blocks and pistons

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/SpigotCraft#188]
left spigot, right vanilla
![http://i.minidigger.me/2016/11/ApCent_16_18-46-03.png](http://i.minidigger.me/2016/11/ApCent_16_18-46-03.png)
http://i.minidigger.me/2016/11/ApCent_16_18-46-03.png

if you remove the block in front of the piston it works just fine

**Comment by okx-code** [comment]
Is that land claimed? Pistons don't push blocks outside claims.

**Comment by MiniDigger** [comment]
......
