### ISSUE TITLE
Jukeboxes play mulitple songs

### ISSUE THREAD

**Issue by IRTHATDUDE** [SpigotMC/SpigotCraft#189]
not sure if this is client side though. when inserted and remove enough times it will play with out the disc and you can do this more than once with mulitple songs after first initiated.

**Comment by IRTHATDUDE** [comment]
and doesn't seem to stop untill all songs are finished in progressive order

**Comment by MiniDigger** [comment]
can't reproduce, can you try to give exact steps? can you also try to do that in vanilla?

**Comment by IRTHATDUDE** [comment]
if you repeatedly play a song it will, continue playing after a certain amount of attempts. and it overlaps if done with more than one song. i will test in vanilla

**Comment by IRTHATDUDE** [comment]
tested on single player vanilla, it does the same thing. So its a bug in 1.11 presumably.

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-36030
