### ISSUE TITLE
/locate command requires exact spelling of features.

### ISSUE THREAD

**Issue by JamieSinn** [SpigotMC/SpigotCraft#192]
eg /locate temple does not work, and requires T to be capitalized.
./locate Temple works.

**Comment by MiniDigger** [comment]
minecraft command, minecraft handles that
its the same for vanilla

**Comment by JamieSinn** [comment]
http://i.imgur.com/e353RlH.png

**Comment by IRTHATDUDE** [comment]
you can just tab
