### ISSUE TITLE
Mobs deal damage without weapons while shield is up.

### ISSUE THREAD

**Issue by JamieSinn** [SpigotMC/SpigotCraft#194]

**Comment by nayoshi** [comment]
wait that isn't normal? wot

**Comment by MiniDigger** [comment]
mcwiki: "Shields: Now block 100%, as opposed to 66%, of the damage dealt in melee combat."

**Comment by JamieSinn** [comment]
![2016-11-16_14 32 29](https://cloud.githubusercontent.com/assets/1538232/20362443/a5f7ec46-ac09-11e6-85a3-14b4cbf4b2a8.png)
![2016-11-16_14 32 17](https://cloud.githubusercontent.com/assets/1538232/20362444/a5ffc04c-ac09-11e6-8fb5-ba0334f11585.png)
![2016-11-16_14 32 19](https://cloud.githubusercontent.com/assets/1538232/20362446/a604b5ca-ac09-11e6-926f-eb6c9161be8d.png)
![2016-11-16_14 32 22](https://cloud.githubusercontent.com/assets/1538232/20362445/a6005264-ac09-11e6-82bd-8ffb0f2d15d9.png)
![2016-11-16_14 32 24](https://cloud.githubusercontent.com/assets/1538232/20362447/a6058bbc-ac09-11e6-8804-9e62b89428ec.png)

http://minecraft.gamepedia.com/1.11#Items_2

**Comment by JamieSinn** [comment]
I was backed up against a wall, this could be vanilla

**Comment by electronicboy** [comment]
Tested between vanilla and spigot, In my test, I noticed that in vanilla, they'd KB off my shield, in spigot, they'd get KB'd and so would I (worth pointing out the addition of myself bouncing into this)

**Comment by JamieSinn** [comment]
I also got kb'd, but as I was against a wall I didn't move.

**Comment by JamieSinn** [comment]
Also took damage from a creeper when I should not have.

**Comment by md-5** [comment]
Not a new bug
