### ISSUE TITLE
Food level refills when right clicking on a cake in a protected area

### ISSUE THREAD

**Issue by paolobarbolini** [SpigotMC/SpigotCraft#195]
Right clicking on a cake in a protected area refills the food level for some seconds, then it returns back to the original level

**Comment by MiniDigger** [comment]
not s spigot bug, @RoboMWM need to fix that :D

**Comment by MiniDigger** [comment]
is the area claimed by yourself?

**Comment by electronicboy** [comment]
Potentially an issue with the client assuming stuff

**Comment by paolobarbolini** [comment]
No, i'm right clicking on the cakes protected in the spawn.
If i place a cake in an area which is not protected it works correctly.

**Comment by BillyGalbreath** [comment]
Its a client/server sync issue and plagues many protection plugins for many years now. Its just a client visual that's wrong, the next hunger packet that gets sent fixes it. I usually send the packet right away when i cancel eating a cake with my own plugin.
