### ISSUE TITLE
Shield does not properly stop fire from zombies and wither effect from wither skeletons

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#196]
Zombie (on fire): https://img.ssamjh.nz/i/u7r33.mp4

Wither skeleton: https://img.ssamjh.nz/i/5aur2.mp4

**Comment by md-5** [comment]
Possibly also 1.10 bug, needs crosschecking

**Comment by ssamjh** [comment]
Same issue with wither skeletons and getting the wither effect. Video uploading now.

**Comment by ScruffyRules** [comment]
![chrome_2016-11-17_07-43-35](https://cloud.githubusercontent.com/assets/5356779/20366143/b987c570-ac99-11e6-9437-25074f189303.png)

**Comment by ssamjh** [comment]
This is NOT an issue in 1.11 Vanilla for both. Just tested it with ScruffyRules on my test server.

**Comment by md-5** [comment]
Shields updated to stop all damage
