### ISSUE TITLE
Elytra bug 1.11

### ISSUE THREAD

**Issue by Lunke1** [SpigotMC/SpigotCraft#197]
Hey, ive encountered an bug with the elytra on the Spigot Testserver.
I reproduced it several times but not in SP and not in latest 1.10 build of spigot on privat server, only on the Spigot testserver.
It happens if you jump and open elytra while jumping, you jump then fall and then your stuck with elytra still flying on the bottom (see video) also others can see it. If i die i still can fly but elytra is gone but on other clients im standing normal, not flying(also in video).
Also mobs cant attack me really only sometimes except creepers they still explode when im in range.

https://youtu.be/I5MJJNJssyY

**Comment by ScuroK** [comment]
i can confirm. same happened to me and another player
![2016-11-16_22 30 46](https://cloud.githubusercontent.com/assets/10480144/20366873/514fa94c-ac4d-11e6-900f-5a7c0366ffcd.png)

**Comment by md-5** [comment]
I really can't reproduce anything buggier than Vanilla already is
