### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by Legoman99573** [SpigotMC/SpigotCraft#200]
When i connect to the server, i get this error. Error doesnt show on the normal minecraft server jar.

![image](https://cloud.githubusercontent.com/assets/7460704/20368660/9d3cb792-ac1a-11e6-9e85-4a324e26afba.png)

The errors and warnings should be labeled.

**Comment by Pokechu22** [comment]
The _error_ is a launcher problem in this case - related to System.out.println.  Dinnerbone's already aware of that set of errors.  It's the soundsystem's fault (soundsystem doesn't use log4j).  It _probably_ happened before you joined the server but System.out was only flushed when the real log message appeared.

The warning is probably a spigot problem though.

**Comment by Legoman99573** [comment]
sorry, it looked like a spigot error at first, but at least i know its fixed in the update of the alpha launcher.
