### ISSUE TITLE
Minecarts On Powered Rails Randomly Teleporting

### ISSUE THREAD

**Issue by Vexentric** [SpigotMC/SpigotCraft#203]
I recorded a video on this bug here: https://youtu.be/jVevrrTJxFA
I am not sure if this is supposed to happen or not, but whenever you place a minecart on a powered rail with a block next to it, the minecart displays a breaking animation and when you enter it, you get teleported to a few blocks away.

Maybe you could use this in the nether to get above the roof or to get outside of the worldborder?

**Comment by Vexentric** [comment]
Also: Sorry for the laggy video, My computer isn't good with recording and gaming at the same time.

**Comment by ssamjh** [comment]
I can confirm this is an issue

https://img.ssamjh.nz/i/430r7.mp4

**Comment by md-5** [comment]
Vanilla issue
