### ISSUE TITLE
Ocelots cannot be tamed / put on a lead / bred

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#204]

**Comment by Yottazoid** [comment]
I was able to do all three. The method is different from wolves.

**Comment by ssamjh** [comment]
@Yottazoid How do you do it, don't you sneak, then right click on the ocelot with raw fish?

**Comment by Yottazoid** [comment]
Yes. You need to wait until the Ocelot is looking at and warking toward you. The full method is here: http://minecraft.gamepedia.com/Ocelot#Taming

**Comment by md-5** [comment]
Hmm, I tried that in Vanilla even and they gave hearts but never changed into cats.

**Comment by Yottazoid** [comment]
Sometimes you need to give them more than one fish. The first time they will give hearts, the rest seems to be a puff of smoke (that might be unintentional). After a few fish, they turned into cats.
