### ISSUE TITLE
Mobs can't levatate when hit by shulker

### ISSUE THREAD

**Issue by SnailzDev** [SpigotMC/SpigotCraft#207]
https://www.dropbox.com/s/ccwvcg5bj0hze8b/javaw%202016-11-16%2019-04-42-587.mp4?dl=0

**Comment by SnailzDev** [comment]
tp to-215 67 413 to see

**Comment by ssamjh** [comment]
I'll try to reproduce it in vanilla.

**Comment by Yottazoid** [comment]
Summoning them with the levitation effect makes them levitate though.

**Comment by md-5** [comment]
![2016-11-17_14 18 45](https://cloud.githubusercontent.com/assets/1007849/20375070/cb792710-acd0-11e6-9924-d29e6d5819a3.png)
![2016-11-17_14 18 25](https://cloud.githubusercontent.com/assets/1007849/20375069/cb758f92-acd0-11e6-8cfa-60b490b52533.png)

**Comment by md-5** [comment]
I think its because the coords you pasted are in a claimed area
