### ISSUE TITLE
Possible structure generation issue

### ISSUE THREAD

**Issue by zedwick** [SpigotMC/SpigotCraft#208]
In the woodland mansion at 5529 81 -760 some of the natural landscape (grass blocks, flowers) can be seen inside near the ceiling.

This is obviously not intended, though I don't know if it is a vanilla issue (or player placed? Couldn't get any help working that out in-game)

**Comment by md-5** [comment]
Vanilla

**Comment by ssamjh** [comment]
![issue picture](https://img.ssamjh.nz/i/i1poe.png)
Reproduced in Vanilla for reference.
