### ISSUE TITLE
Wrong soung ID in EntityWither class

### ISSUE THREAD

**Issue by Zeruska** [SpigotMC/SpigotCraft#213]
The correct wither spawn sound ID is: 1023

> // CraftBukkit start - Use relative location for far away sounds
// this.world.a(**_1023_**, new BlockPosition(this), 0);
.
.
.
if (distanceSquared > viewDistance * viewDistance) {
double deltaLength = Math.sqrt(distanceSquared);
double relativeX = player.locX + (deltaX / deltaLength) * viewDistance;
double relativeZ = player.locZ + (deltaZ / deltaLength) * viewDistance;
player.playerConnection.sendPacket(new PacketPlayOutWorldEvent(**_1013_**, new BlockPosition((int) relativeX, (int) this.locY, (int) relativeZ), 0, true));
} else {
player.playerConnection.sendPacket(new PacketPlayOutWorldEvent(**_1013_**, new BlockPosition((int) this.locX, (int) this.locY, (int) this.locZ), 0, true));
}
.
.
.
// CraftBukkit end

**Comment by ScruffyRules** [comment]
For 1.11 or everywhere?

**Comment by Zeruska** [comment]
ID changed after 1.8.7 (from **_1013_** to **_1023_**), but CraftBukkit 1.9.x, 1.10.x and 1.11 still used **_1013_**.

**Comment by ScruffyRules** [comment]
Cheers for the info.

**Comment by md-5** [comment]
Thanks
