### ISSUE TITLE
Non-ops can place structure blocks but can't break them

### ISSUE THREAD

**Issue by Yamakaja** [SpigotMC/SpigotCraft#214]
What is interesting about this: The client actually doesn't appear to place the block, but the server does anyway.

**Comment by MiniDigger** [comment]
thats fixed https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a951a88398d88c4823aedde5e88beb352fa38b64

**Comment by Yamakaja** [comment]
Oh, i guess that change wasn't live yet
