### ISSUE TITLE
Hopper on a furnace with an item inside crashes SPMC

### ISSUE THREAD

**Issue by TNTUP** [SpigotMC/SpigotCraft#216]
See here: https://hub.spigotmc.org/jira/browse/SPIGOT-2793

I noticed issues with furnaces on my test server while placing, LWC/TNTRun/Prism/WorldGuard complains about the same error TileEntityFurnace cannot be cast to TileEntityLootTables. Doing this step crashes the server outputting the same error I'm getting and maybe others. I'm even able to reproduce it on SpigotCraft. I did a gif here http://i.qcfb.ca/20161118033653.gif

**Comment by ssamjh** [comment]
+1 Can also confirm this issue.

Issue from the server log https://paste.ssamjh.nz/view/raw/9732b7d1

Crash.txt here https://paste.ssamjh.nz/view/raw/7235b668

This issue is not present in Vanilla single player.
