### ISSUE TITLE
Error with SQL connection

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#217]
[https://hub.spigotmc.org/jira/browse/SPIGOT-2794](https://hub.spigotmc.org/jira/browse/SPIGOT-2794)

When a plugin use MySQL, i get a lot of error, all the time the same error for all plugins to use MySQL.

> [10:28:52] [Server thread/WARN]: Fri Nov 18 10:28:52 CET 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by KatsuroKurosaki** [comment]
If you have the connection URL, just append useSSL=false to the end, and it will disappear.

Example: jdbc:mysql://localhost:3306/database?autoReconnect=true&useSSL=false

**Comment by ghost** [comment]
i don't have connection URL for all plugin, sometimes they are variables in the configuration file, so I can not add that.
