### ISSUE TITLE
Shulker bug

### ISSUE THREAD

**Issue by GoliathLabs** [SpigotMC/SpigotCraft#219]
[http://prnt.sc/d9c6ii](http://prnt.sc/d9c6ii)

Just look at this pic. (Just a bug in 1.11 or in Spigot)

Edit.: There is a big amout of projectiles, put together in the shulker. It won|t move out just placed in the middle of the shulker.

**Comment by md-5** [comment]
That pic tells me nothing

**Comment by GoliathLabs** [comment]
There was a big amout of projectiles, which only moved in the shulker. @md-5
