### ISSUE TITLE
Greylisting based on invites.

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#22]
Maintaining a greylist, or whitelist will become boring and difficult at scale, i'd suggest the following.
- New players will spawn as `noobs` and can only talk and walk.
- New players have to be `vouched` by another player, which allows them to start playing.

However, there are a few strings attached.
- If the player you vouched for starts griefing, your vouch rights will be revoked for X hours/weeks
- If you keep bringing in bad people, your vouch rights will be revoked.

See - http://www.tweakcraft.net/ranks?language=english for more information.

**Comment by JamieSinn** [comment]
Does a plugin exist for this?

**Comment by RoboMWM** [comment]
> If the player you vouched for starts griefing, your vouch rights will be revoked for X hours/weeks

How will this be determined?

**Comment by JamieSinn** [comment]
I'd assume by logblock.

**Comment by RoboMWM** [comment]
Automated (check if player is destroying another player's placed blocks) or manual checks..?

**Comment by ctian1** [comment]
How are players' "criminal" records managed?

**Comment by jeff142** [comment]
Ive actually seen servers ware this works good, the problems i can see is how do you start it out, like do donators get the "starting" vouches or, over X post?

**Comment by Cldfire** [comment]
I believe it was going to be so that forum accounts were linked to the server, and you'd have to have x amount of posts to play.

**Comment by jeff142** [comment]
So you would be able to invite people under the post treshold?

**Comment by RoboMWM** [comment]
In order to link forum accounts you'd need to verify an MC account via the forums though...

**Comment by jeff142** [comment]
I'm just not seeing how this invite thing would work, Could i just invite anyone i wanted, or only people above the threshold?

**Comment by Cldfire** [comment]
Anyone can join, but they can't chat / interact with the world. Any members above x posts can chat / interact with the world.

That was the original idea, but that would encourage post spam IMO.

**Comment by gardenerik** [comment]
Or maybe create some kind of test, that will add player to whitelist?

**Comment by ghost** [comment]
I think a mix of a post and vouch system would be interesting.
