### ISSUE TITLE
ClassCastException (TileEntityFurnace ->TileEntityLootable) = Crash

### ISSUE THREAD

**Issue by LTNico** [SpigotMC/SpigotCraft#220]
Crash :

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 19/11/16 21:06
Description: Ticking block entity

java.lang.ClassCastException: net.minecraft.server.v1_11_R1.TileEntityFurnace cannot be cast to net.minecraft.server.v1_11_R1.TileEntityLootable
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftLootable.<init>(CraftLootable.java:17)
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftFurnace.<init>(CraftFurnace.java:15)
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.getState(CraftBlock.java:276)
	at net.minecraft.server.v1_11_R1.TileEntity.getOwner(TileEntity.java:273)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.s(TileEntityHopper.java:209)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.o(TileEntityHopper.java:130)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.F_(TileEntityHopper.java:118)
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1519)
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftLootable.<init>(CraftLootable.java:17)
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftFurnace.<init>(CraftFurnace.java:15)
	at org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.getState(CraftBlock.java:276)
	at net.minecraft.server.v1_11_R1.TileEntity.getOwner(TileEntity.java:273)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.s(TileEntityHopper.java:209)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.o(TileEntityHopper.java:130)
	at net.minecraft.server.v1_11_R1.TileEntityHopper.F_(TileEntityHopper.java:118)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.server.v1_11_R1.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.server.v1_11_R1.BlockHopper)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-304,11,-6105), Chunk: (at 0,0,7 in -19,-382; contains blocks -304,0,-6112 to -289,255,-6097), Region: (-1,-12; contains chunks -32,-384 to -1,-353, blocks -512,0,-6144 to -1,255,-5633)
	Actual block type: ID #154 (tile.hopper // net.minecraft.server.v1_11_R1.BlockHopper)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1519)
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635)

-- Affected level --
Details:
	Level name: world
	All players: 14 total; [EntityPlayer['Krysix_'/306, l='world', x=10241,71, y=51,00, z=10546,29](Krysix_ at 10241.706090149559,51.0,10546.28575674534), EntityPlayer['demon10000'/333, l='world', x=-53,72, y=64,77, z=81,36](demon10000 at -53.71790953417879,64.76636799395752,81.35833539919886), EntityPlayer['TheTweep'/1000, l='world', x=-301,13, y=10,00, z=-6105,62](TheTweep at -301.12661815315744,10.0,-6105.621083620411), EntityPlayer['Wolfseen'/1158, l='world', x=10240,96, y=51,00, z=10547,48](Wolfseen at 10240.960062622968,51.0,10547.48118438136), EntityPlayer['Erisium_Azgox'/1279, l='world', x=584,32, y=63,00, z=585,70](Erisium_Azgox at 584.3175574014069,63.0,585.6999999880791), EntityPlayer['monky3597'/1343, l='world', x=23695,48, y=40,00, z=-24490,79](monky3597 at 23695.475708026224,40.0,-24490.79263983472), EntityPlayer['Hunter_Craw'/1981, l='world', x=-1565,47, y=23,00, z=331,61](Hunter_Craw at -1565.4728136976114,23.0,331.60552746264136), EntityPlayer['demembreur10'/2144, l='world', x=-81,11, y=72,00, z=62,90](demembreur10 at -81.11411269519257,72.0,62.8956650542096), EntityPlayer['Tyzo_3101'/2148, l='world', x=-237,69, y=11,00, z=-6207,34](Tyzo_3101 at -237.6937798187883,11.0,-6207.338041697049), EntityPlayer['gabriel93'/2418, l='world', x=-73,30, y=57,00, z=7992,52](gabriel93 at -73.30449393490562,57.0,7992.517461238819), EntityPlayer['yNico'/2653, l='world', x=177,73, y=76,49, z=122,99](yNico at 177.72965301802284,76.49390748022948,122.99121673328052), EntityPlayer['CORTESPaul18'/3221, l='world', x=134,49, y=67,00, z=201,97](CORTESPaul18 at 134.49477036832292,67.0,201.96645068564374), EntityPlayer['pachanat'/3304, l='world', x=1447,52, y=70,50, z=-2020,29](pachanat at 1447.523897559512,70.5,-2020.2908805616703), EntityPlayer['Straight1'/3896, l='world', x=95,61, y=72,25, z=837,81](Straight1 at 95.61341122034187,72.24918707874468,837.8097037176897)]
	Chunk stats: ServerChunkCache: 4657 Drop: 0
	Level seed: 2812362019228110607
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (166,71,161), Chunk: (at 6,4,1 in 10,10; contains blocks 160,0,160 to 175,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 84183753 game time, 32619665 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 104754 (now: false), thunder time: 5657 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1805686040 bytes (1722 MB) / 4167430144 bytes (3974 MB) up to 8160477184 bytes (7782 MB)
	JVM Flags: 7 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xmn4G -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-16c940b-0805f60 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT) true
   Plugins: { LyneApi v1.0 fr.lyneteam.nico.lyne.api.Api [Nicolas Demailly], LyneCraft v1.0 fr.lyneteam.nico.lynecraft.LyneCraft [Nicolas Demailly],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:172), java.lang.Thread.run(Thread.java:745)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:255), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read(BufferedInputStream.java:265), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_11_R1.DedicatedServer$2.run(DedicatedServer.java:84)], RUNNABLE Thread-20: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], TIMED_WAITING Thread-16: [java.lang.Thread.sleep(Native Method), fr.lyneteam.nico.lyne.api.GlobalTimer.run(GlobalTimer.java:24)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Thread-23: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Netty Epoll Server IO #2: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], TIMED_WAITING Abandoned connection cleanup thread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1607), org.bukkit.craftbukkit.v1_11_R1.CraftCrashReport.call(CraftCrashReport.java:30), net.minecraft.server.v1_11_R1.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_11_R1.CrashReport.h(CrashReport.java:126), net.minecraft.server.v1_11_R1.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_11_R1.CrashReport.a(CrashReport.java:320), net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1522), net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635), net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806), net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399), net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675), net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574), java.lang.Thread.run(Thread.java:745)], RUNNABLE Thread-21: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-30: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-22: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Netty Epoll Server IO #3: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], RUNNABLE Thread-13: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.scoreboard.ScoreboardManager.run(ScoreboardManager.java:103)], RUNNABLE Thread-17: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-28: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-29: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-26: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], RUNNABLE Thread-18: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_11_R1.DedicatedServer$1.run(DedicatedServer.java:59)], RUNNABLE Thread-19: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-27: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_11_R1.FileIOThread.c(SourceFile:51), net.minecraft.server.v1_11_R1.FileIOThread.run(SourceFile:30), java.lang.Thread.run(Thread.java:745)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Thread-15: [java.lang.Thread.sleep(Native Method), fr.lyneteam.nico.lyne.api.scoreboard.ScoreboardAnimation.run(ScoreboardAnimation.java:20)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164), sun.java2d.Disposer.run(Disposer.java:148), java.lang.Thread.run(Thread.java:745)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], RUNNABLE Thread-24: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE Thread-25: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.util.LynePlayer.run(LynePlayer.java:84)], RUNNABLE DestroyJavaVM: [], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_11_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:27), java.lang.Thread.run(Thread.java:745)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)], RUNNABLE Signal Dispatcher: [], RUNNABLE Thread-9: [java.lang.Thread.suspend0(Native Method), java.lang.Thread.suspend(Thread.java:1029), fr.lyneteam.nico.lyne.api.database.SqlDatabase.run(SqlDatabase.java:52)], TIMED_WAITING Thread-10: [java.lang.Thread.sleep(Native Method), fr.lyneteam.nico.lyne.api.TaskExecutor.run(TaskExecutor.java:28)],}
   Recent tasks from 1117-1147{}
	Profiler Position: N/A (disabled)
	Player Count: 14 / 100; [EntityPlayer['Krysix_'/306, l='world', x=10241,71, y=51,00, z=10546,29](Krysix_ at 10241.706090149559,51.0,10546.28575674534), EntityPlayer['demon10000'/333, l='world', x=-53,72, y=64,77, z=81,36](demon10000 at -53.71790953417879,64.76636799395752,81.35833539919886), EntityPlayer['TheTweep'/1000, l='world', x=-301,13, y=10,00, z=-6105,62](TheTweep at -301.12661815315744,10.0,-6105.621083620411), EntityPlayer['Wolfseen'/1158, l='world', x=10240,96, y=51,00, z=10547,48](Wolfseen at 10240.960062622968,51.0,10547.48118438136), EntityPlayer['Erisium_Azgox'/1279, l='world', x=584,32, y=63,00, z=585,70](Erisium_Azgox at 584.3175574014069,63.0,585.6999999880791), EntityPlayer['monky3597'/1343, l='world', x=23695,48, y=40,00, z=-24490,79](monky3597 at 23695.475708026224,40.0,-24490.79263983472), EntityPlayer['Hunter_Craw'/1981, l='world', x=-1565,47, y=23,00, z=331,61](Hunter_Craw at -1565.4728136976114,23.0,331.60552746264136), EntityPlayer['demembreur10'/2144, l='world', x=-81,11, y=72,00, z=62,90](demembreur10 at -81.11411269519257,72.0,62.8956650542096), EntityPlayer['Tyzo_3101'/2148, l='world', x=-237,69, y=11,00, z=-6207,34](Tyzo_3101 at -237.6937798187883,11.0,-6207.338041697049), EntityPlayer['gabriel93'/2418, l='world', x=-73,30, y=57,00, z=7992,52](gabriel93 at -73.30449393490562,57.0,7992.517461238819), EntityPlayer['yNico'/2653, l='world', x=177,73, y=76,49, z=122,99](yNico at 177.72965301802284,76.49390748022948,122.99121673328052), EntityPlayer['CORTESPaul18'/3221, l='world', x=134,49, y=67,00, z=201,97](CORTESPaul18 at 134.49477036832292,67.0,201.96645068564374), EntityPlayer['pachanat'/3304, l='world', x=1447,52, y=70,50, z=-2020,29](pachanat at 1447.523897559512,70.5,-2020.2908805616703), EntityPlayer['Straight1'/3896, l='world', x=95,61, y=72,25, z=837,81](Straight1 at 95.61341122034187,72.24918707874468,837.8097037176897)]
	Is Modded: Definitely; Server brand changed to 'Spigot'
	Type: Dedicated Server (map_server.txt)`

**Comment by md-5** [comment]
Update
