### ISSUE TITLE
give spawn eggs

### ISSUE THREAD

**Issue by Ironic8b498** [SpigotMC/SpigotCraft#223]
I'm using this command but I get, "error:null" in return 
 /give <playername> spawn_egg 1 0 {EntityTag:{id:minecraft:wither_skeleton}}

**Comment by md-5** [comment]
You need to use minecraft:give if a plugin overrides give

**Comment by Ironic8b498** [comment]
thanks

**Comment by Yamakaja** [comment]
Additionally correct give syntax would be /give <PLAYER> <sth>
