### ISSUE TITLE
Replace HeroChat

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#227]
We need a new chat plugin.
Old HeroChat does not work with 1.12 (deprecated methods removed), and the new version is premium.

**Comment by MiniDigger** [comment]
venture chat is a good alternative, purpleirc can hook I to it like it does with herochat https://www.spigotmc.org/resources/venturechat.771/

**Comment by ghost** [comment]
You're saying you can't download premium resources for free with your fancy administrator account?

**Comment by md-5** [comment]
I'm saying I'm not going to download them and publish it here.

**Comment by md-5** [comment]
Using EssentialsChat
