### ISSUE TITLE
Sleeping

### ISSUE THREAD

**Issue by nklyshko** [SpigotMC/SpigotCraft#229]
When I sleeping bed, then server kick me with "flying is not enabled..."

**Comment by md-5** [comment]
Thanks, will look into it.

**Comment by md-5** [comment]
Managed to reproduce this only once. Could potentially be a Vanilla issue or specific to the way in which you enter your bed.

**Comment by Yottazoid** [comment]
There is currently a vanilla bug where if you jump then mount an entity or other, the server will kick you for flying.

**Comment by md-5** [comment]
1.11.2 or only snapshots?

**Comment by Yottazoid** [comment]
Reported every version from 1.9.
> https://bugs.mojang.com/browse/MC-98727

**Comment by md-5** [comment]
Vanilla, happens in older versions
