### ISSUE TITLE
Advancement command is missing ?

### ISSUE THREAD

**Issue by crazyhorse961** [SpigotMC/SpigotCraft#232]
Hello!
I don't know if is intentional, but i see that the /advancement command (http://minecraft.gamepedia.com/Commands#advancement) isn't avaiable. Are you planning on adding it?
On Vanilla i'm sure this doesn't occurs

**Comment by md-5** [comment]
Its there, you just dont have permission.
/advancement would tell you as much

**Comment by crazyhorse961** [comment]
Mh.. but it doesn't complete on tab..? It shall even if you don't have the permission (like  /recipe).

**Comment by md-5** [comment]
Because you don't have permission

**Comment by crazyhorse961** [comment]
For the update above (the edit), /recipe is from Essentials, so.. not a bug..
