### ISSUE TITLE
1.12 Bug - Illusioner's Arrows

### ISSUE THREAD

**Issue by GalHorowitz** [SpigotMC/SpigotCraft#236]
Seems like illusioners can't hit players. Their main attack is shooting arrows, and I spawned more than 10 of them. Not one managed to hit a shot. 50% of shots missed, and 50% just bounced off me. I was in survival & diamond armor.

**Comment by ssamjh** [comment]
Tried in survival + creative?

**Comment by GalHorowitz** [comment]
They won't target creative players.

**Comment by md-5** [comment]
iirc illusioners aren't implemented outside of /summon yet, so aren't expected to work
You should definitely check Vanilla on this, especially because we don't even import any illusioner code.

**Comment by ssamjh** [comment]
No like creative world and survival world xD

**Comment by GalHorowitz** [comment]
Ok md5. Will check vanilla.

**Comment by GalHorowitz** [comment]
Never mind. Creative plots issue. Sorry!
