### ISSUE TITLE
Why are Builders allowed to use LogBlock lookups?

### ISSUE THREAD

**Issue by ctian1** [SpigotMC/SpigotCraft#24]

**Comment by RoboMWM** [comment]
Why not let anyone use it?

Update: Doesn't seem builders are allowed to use LogBlock lookups anyways...?

**Comment by jeff142** [comment]
:-1:

I honestly don't see any reason that they should not be able to,

**Comment by JamieSinn** [comment]
Based on their perm level, I thought it was about right to have it.
If you notice, only admins can do anything with it. This just allows builders to check who greifed if needed.
