### ISSUE TITLE
Mobs alive in the daylight

### ISSUE THREAD

**Issue by Fonzee9** [SpigotMC/SpigotCraft#242]
On the spigot test server mobs like zombies, skeletons are alive in the daylight.

**Comment by Fonzee9** [comment]
Seems to be a one time thing.

**Comment by chuushi** [comment]
I came across a skeleton that wasn't burning as well. It kept making steaming (fire extinguishing) sound and particle, but it didn't burn in fire.

**Comment by md-5** [comment]
I'm definitely seeing burning skeletons and zombies.

**Comment by BillyGalbreath** [comment]
Possible it was raining and you have weather disabled in client? Rain stops mobs from burning, but some clients can turn off weather visuals (optifine) so it looks like they live during the day. They will try to burn on ckient, but rain extinguishes the fire before damaging them.

**Comment by md-5** [comment]
I don't think there is a wide choice of modded clients for snapshots

**Comment by Fonzee9** [comment]
![18195514_1931483403756183_1985333748_o](https://cloud.githubusercontent.com/assets/21323258/25438126/7d45f1b8-2a66-11e7-9c7b-0b270326147a.jpg)

On the side of that picture is a zombie on the side not burning

**Comment by Pokechu22** [comment]
FYI: <kbd>F2</kbd> is a thing :3 (also, I note that clouds are on on Fancy mode, so it's not a case of weather being disabled in any way)

**Comment by Gaxan** [comment]
I noticed this today. The skeletons and zombies were not burning. 
I could hear lightning but no rain particles were appearing but occasionally. I think it's an issue with the rain particles not appearing or being seen while it's raining.

**Comment by 2008Choco** [comment]
They seem to be burning perfectly fine for me.
![2017-04-26_21 42 44](https://cloud.githubusercontent.com/assets/10508906/25464251/581fbdca-2ac9-11e7-973b-3710a9fe5d95.png)

The only thing I could think of is that the zombie has an item on its head and it's not properly rendering? It's certainly not raining in the screenshot provided by @Fonzee9, so I'm not sure why that one, in particular, is not burning. However, the zombie on the right of my image was not burning for a good 5 seconds until it finally updated then started burning. Perhaps this is the same thing happened to the zombie in the screenshot above and it had yet to update.

As for @Gaxan's suggestion of rain particles not displaying, that would be a client-side issue. Though it has rained countless times on the server, and particles are displaying just fine

**Comment by chuushi** [comment]
My client is vanilla (no mods for snapshots :I ) and shows rain particles (and whenever it rains, someone toggles it away).  It may be the delay from when the server realizes that the mob is standing in direct sunlight, but mobs occasionally didn't burn.

**Comment by GenRedWolf** [comment]
So I had the same problem last night with the rain starting and then immediately stopping the visual. However the mods responded (not burning) as if it was still raining. Checking F3, the light level stated is was 15. Later (say 12 AM EST), during a thunderstorm, the rain started for a second but stopped. Thunder kept going all day and mods were spawning, but no rain. F3 still showed light level 15. When the rain was stopping the rain particles appeared for a second and then stop as the rain stopped.

**Comment by 2008Choco** [comment]
> So I had the same problem last night with the rain starting and then immediately stopping the visual. However the mods responded (not burning) as if it was still raining. Checking F3, the light level stated is was 15. Later (say 12 AM EST), during a thunderstorm, the rain started for a second but stopped. Thunder kept going all day and mods were spawning, but no rain. F3 still showed light level 15. When the rain was stopping the rain particles appeared for a second and then stop as the rain stopped.

This makes much more sense now. I was on the server last night and lightning was going off constantly although no rain was displaying. I do notice the rain toggling off automatically as well, because every time it turns off, I'm not the one doing so. I don't even have access to /toggledownfall. Could it be perhaps a plugin that is turning it off? Clearly the Minecraft server still THINKS its raining when in fact the clients are not aware of the rain

**Comment by md-5** [comment]
Light level isn't affected by rain

**Comment by md-5** [comment]
I've found and fixed the bug I think (please test)

**Comment by BillyGalbreath** [comment]
> Light level isn't affected by rain

It actually lowers the light level by 3, bringing it to 12 in full daylight. If its a thunderstorm then the light is lowered by 5, bringing it to 10 in full daylight (although it is rendered brighter in client at 11.5 with a blue tint).

http://minecraft.gamepedia.com/Rain
http://minecraft.gamepedia.com/Thunderstorm

**Comment by md-5** [comment]
Yes, but not on the F3 debug menu block / sky light.

**Comment by md-5** [comment]
The actual  issue was just currently online clients not getting weather updates for natural weather changes. It couldn't be easily reproduced because the updates were sent for command changes / relogs.

**Comment by BillyGalbreath** [comment]
> Yes, but not on the F3 debug menu block / sky light.

Well, yeah. F3 debug also says its 15 light level at night time as well.. Just wanted to clarify the light levels. I'm glad its been fixed, though ^_^
