### ISSUE TITLE
Dying removes all known recipes

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#247]
I cannot confirm this without rebooting SpigotCraft, however, I believe that if it is rebooted, all known recipes disappear.

Tested on Vanilla and it was fine.

**Comment by md-5** [comment]
I'm not sure on this.
They're definitely being saved on restart, however your nbt file does have no recipes stored in it.
May be a case of people using the /minecraft:recipe command, but I'm not sure.

**Comment by md-5** [comment]
Death + Relog = Lose all Recipes.
Fix committed, will be available probably with 17w17a.
