### ISSUE TITLE
Illegal Enchantment Kicks Client from Server

### ISSUE THREAD

**Issue by TreyRuffy** [SpigotMC/SpigotCraft#249]
##### In the video, I go on a vanilla server to make sure that this is a Spigot related issue, then I go on the 1.12 Spigot server and type the same command to get the same item, except, when I click the item on the Spigot server, the Client crashes.
[Video](https://youtu.be/I0IeqMmajYw)

**Comment by md-5** [comment]
I highly doubt this is new to 1.12

**Comment by ssamjh** [comment]
Will test on older versions.

**Comment by ssamjh** [comment]
Works in single player Vanilla 1.11.2 fine.

On Spigot 1.11.2 latest build (as of 10 minutes ago) running the command will give you a sword however it has no enchantment glow on it. But I'm not getting disconnected.

SpigotCraft = disconnect.

Singleplayer 17w16b works fine. With enchantment glow. Same on shot.ssamjh.nz. Currently, seems isolated to the latest Spigot snapshot build.

I have a feeling it's failing to display a enchant message in the lore. No versions do, however, maybe Spigot is trying to and failing?

**Comment by md-5** [comment]
It happens in 1.11.2 craftbukkit but not Spigot

**Comment by md-5** [comment]
Ported the appropriate patch from Spigot.
Will be active in 17w17a
