### ISSUE TITLE
Start with pex 2

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/SpigotCraft#25]
I would suggest starting off with the new pex version to save trouble later

**Comment by RoboMWM** [comment]
Don't think it's considered stable(?) and afaik there's no docs on it

**Comment by ghost** [comment]
PEX 2 doesn't handle permissions.
http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/44640-pex-2-0-information/?page=2#p32

**Comment by PhanaticD** [comment]
thats from 2013 and isnt what actually happened

**Comment by JamieSinn** [comment]
Not sure why PEX and not GM

**Comment by RoboMWM** [comment]
Anything _but_ GM please...

**Comment by PhanaticD** [comment]
No one sane uses GM

**Comment by Cldfire** [comment]
Er... No, don't use GM.

**Comment by ghost** [comment]
Can someone please explain why `permissionsEx` shouldn't be used? As far as i can see it's only going to handle permissions on this server, sure it's messy in some places but it works fine.

**Comment by HappyHarm** [comment]
@Chnkr They are going to use PEX right? Unless they just put it in the plugins folder for the fun...

**Comment by TomLewis** [comment]
Why would anyone use Pex Over Groupmanager, GM is 1000 times more stable, dousnt have the millions of bugs Pex does either.

**Comment by Terrobility** [comment]
Why not use zPermissions then?
