### ISSUE TITLE
minecraft:kill command causes the server to crash

### ISSUE THREAD

**Issue by electronicboy** [SpigotMC/SpigotCraft#251]
Only tested this once, for obvious reasons, however executing the command to clear up a few dozen parrots from the world `/minecraft:kill @e[type=parrot,r=10]` triggered the server to crash

**Comment by ssamjh** [comment]
I ran this with a capital P so - /minecraft:kill @e[type=Parrot,r=10] - and it didn't crash.
Odd

**Comment by electronicboy** [comment]
I probably screwed up the command and capital P was required, I blame MiniDigger for that; However, shouldn't really crash on a bad command :D

**Comment by ssamjh** [comment]
True, I will test it later when less people are on.

**Comment by ssamjh** [comment]
I tried a few combinations, and nothing happening. Tried with names parrots, untamed, and tamed.
Lowercase and uppercase act the same.

**Comment by md-5** [comment]
So I looked at the crash reports, and the crash report you're speaking of is a watchdog crash.
The watchdog does show parrots, but it shows them in the normal tick loop.
Maybe there were more than a "few dozen parrots" and the server was already on its way to crashing before the command was issued?

**Comment by MiniDigger** [comment]
the server definetly was on low tps. maybe the kill started to kill stuff and the newly spawned entities (drops, xp) killed it.

**Comment by electronicboy** [comment]
Could be, the crash felt horribly in time with me running the command, nor do I recall the server feeling like it was already locked up to a sense, but; I recall the TPS hitting around 6.7 as seen in the channel, so it's not like it was running anywhere in a stable state
If it's a watchdog crash, I'd feel comfortable attributing it to just a timeout due to the lag

**Comment by md-5** [comment]
The watchdog is 60 seconds however.
So either 1) It crashed 60 seconds after you ran the command, or 2) It had already begun to crash almost 60 seconds before you ran the command

**Comment by electronicboy** [comment]
It crashed as I ran the command, so must have been on its way out 60 seconds before and hit the timing bang on to feel like the command did it
