### ISSUE TITLE
PermissionsEX backend SQL

### ISSUE THREAD

**Issue by Savag3life** [SpigotMC/SpigotCraft#254]
Just as a suggestion, you guys should change the PermissionsEX backend to SQL rather then flat file. Change the file plugins/permissionsEX/config.cfg to the following.

```
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://DATABASEIP/DATABASE USERNAME
      user: DATABASE USERNAME
      password: DATABASE PASSWORD
updater: true
alwaysUpdate: false
```
All that is needed is to make the changes replacing 
- DATABASEIP - to the IP address of the hosted SQL server
- DATABSE USERNAME- to the Username of the PermissionsEX table
- DATABASE PASSWORD - Password to the table

Then restart the server or reload permissionsEX (/pex reload), and change the backend configuration type in-game (/pex backend sql), and import the flatfile (/pex import file). Reload, and you are good.

**Comment by ElieTGM** [comment]
I don't see why they should change to SQL, it's just a temporary test server.

**Comment by Savag3life** [comment]
Is it only a test server? I was under the impression that it was a community server. If it is temp, never mind.

**Comment by chuushi** [comment]
Server aside, what are the benefits in moving PEx from flat file to MySQL?  People online suggests staying on flat file for small servers.  I use .yaml for the ease of direct config modification.

MySQL would make more sense for something with big data that grows continuously, such as block/action loggers.

**Comment by md-5** [comment]
+ yaml allows us to track changes in this repo
