### ISSUE TITLE
Tamed Parrots are similar to a Player

### ISSUE THREAD

**Issue by Phloxz** [SpigotMC/SpigotCraft#258]
Got a small issue ( don't know if this has been already fixed )
When Parrots get tamed, and player's kill them, a death message will appear like "Parrot has been killed by <NAME>"
And also for example when a creeper is nearby, the "hiss" sound will appear but the creeper won't explode, so they are similar to beeing triggered as a player

**Comment by Classsic36** [comment]
The "hiss" sound is the parrots trying to imitate the creepers since they don't have a neutral/regular sound.

**Comment by Phloxz** [comment]
LoL ok, thanks for the reply

**Comment by md-5** [comment]
All of this sounds intentional

**Comment by md-5** [comment]
This is Vanilla
