### ISSUE TITLE
Jumping on farmland to return to dirt gets player stuck temporarily

### ISSUE THREAD

**Issue by GenRedWolf** [SpigotMC/SpigotCraft#260]
Steps to repeat: 
Till about 4x8 dirt to farmland. 
Jump up on the farmland while looking down.
About 25% of the time you will get stuck and vibrate for a few seconds.
After a bit you break free without taking damage. 

Seems to be a return of this bug: https://bugs.mojang.com/browse/MC-104259

**Comment by 2008Choco** [comment]
This is a vanilla issue ;) You even mentioned so in your ticket. We can't do much about vanilla issues
