### ISSUE TITLE
advancements "enter the nether" and "nether:root" don't work

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#261]
The advancements "enter the nether" and "nether:root" worked in 17w16b but no more in 17w17b.
They work in vanilla 17w17b.
Mojang changed the condition from
"trigger": "minecraft:enter_block", "conditions": { "block": "minecraft:portal" }
to
"trigger": "minecraft:changed_dimension", "conditions": { "to": "the_nether" }
Maybe the changed_dimension trigger is missing or some trouble with the multiverse plugin ...

**Comment by md-5** [comment]
Will be in a new build soon

**Comment by md-5** [comment]
New build is up.

**Comment by RunaMC** [comment]
I can confirm it is fixed and the advancement "end:root" works too!
I'm looking happily forward to the 1.12 release! Thank you very much!
