### ISSUE TITLE
advancement "deflect arrow" does not work

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#262]
The advancement "deflect arrow" does not work in 17w17b and blocking an arrow does not play the blocking sound. Both work in vanilla 17w17b.

"trigger": "minecraft:entity_hurt_player",
"conditions": { "damage": { "type": { "is_projectile": true }, "blocked": true } }

**Comment by md-5** [comment]
https://www.spigotmc.org/threads/stripping-down-entitydamageevent-damagemodifier.194446/page-3#post-2390560

Gonna be a hard fix this...

**Comment by md-5** [comment]
This code is so stupidly unmaintainable, but it should be fixed for the next release.
I'd appreciate someone to test it.
Blocking sounds isn't fixed and is an existing bug.

**Comment by md-5** [comment]
New build is up, would appreciate testing.

**Comment by RunaMC** [comment]
The advancement works now! Still no blocking sounds as announced.
Thank you for your great job!
