### ISSUE TITLE
Can not place sapling on dirt block with air immediately below

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#264]
Can not place a sapling on a dirt block if either of the two blocks directly below the dirt block are air.

May be an issue with GriefPrevention on the Spigot test server.  Can not confirm without plugin on test server.

Does not occur on Vanilla.

Minecraft 17w17b
Java 1.8.0_131 64bit
Debian 8  Linux 4.10.13
nVidia 378.13

**Comment by 2008Choco** [comment]
I can confirm that this is a "feature" (or bug, I'm not quite sure) at the fault of GriefPrevention.
![2017-05-01_18 01 49](https://cloud.githubusercontent.com/assets/10508906/25596672/61841cda-2e98-11e7-9cca-713c1ddcdc7b.png)
![2017-05-01_18 01 59](https://cloud.githubusercontent.com/assets/10508906/25596671/6183f11a-2e98-11e7-9090-fd8f36ca1162.png)
(I was too lazy to take a video). When attempting to do this within a claim, it seems as though everything works perfectly fine. Outside of the claim, however, it will not permit me to do so

**Comment by klugemonkey** [comment]
If you have at least 2 solid blocks under the dirt, it will work.  Seems like a "feature", but non-vanilla behavior.   I'll check the GP docs.

**Comment by klugemonkey** [comment]
Just thinking, there is no claim, so could be WorldGuard as well.

**Comment by 7rory768** [comment]
Doesn't occur in the plotworld

**Comment by RunaMC** [comment]
You can place the sapling if your inside your own claim!
You can even place it outside your claim, if you click on the side of an adjacent block.

**Comment by klugemonkey** [comment]
Well, now its working on my island.  I will have to test again outside my claim.

**Comment by klugemonkey** [comment]
Right, so in the claim, works, outside, doesn't, and on creative world in a plot works.  Plot is not claimed with GP, but with WorldGuard, so maybe it's a WG issue?

**Comment by klugemonkey** [comment]
I can not reproduce the adjacent block click technique

**Comment by klugemonkey** [comment]
OK, I can now, but the adjacent block must also satisfy the criteria and have no air blocks in the two blocks below the dirt block.

**Comment by klugemonkey** [comment]
Issue so far is only on world, not on world_nether or plots, so maybe it is GP since it is disabled for those worlds.

**Comment by klugemonkey** [comment]
Maybe it's LimitSkyTrees feature on GP.

**Comment by klugemonkey** [comment]
OK, so I'm 100% sure this is the LimitSkyTrees feature of GP, so this issue will be closed.
