### ISSUE TITLE
"New recipes unlocked" promoted while pulling items from creative mode.

### ISSUE THREAD

**Issue by k-jiang** [SpigotMC/SpigotCraft#266]
Client promotes "recipes unlocked" message when obtain items in creative mode. From my point of view, new recipes should never be "unlocked" in creative since you literally don't need to craft anything. Not sure if it is a vanilla "feature" or a bug in Spigot.

**Comment by MiniDigger** [comment]
> Not sure if it is a vanilla "feature" or a bug in Spigot.

be sure to test this in vanilla (with both internal and external server)

**Comment by EazyFTW** [comment]
It's vanilla.
