### ISSUE TITLE
Mobs 'leaking' past fences

### ISSUE THREAD

**Issue by GenRedWolf** [SpigotMC/SpigotCraft#268]
Several times now I've noticed tame mobs leaking past their fence.

I've placed several cows in fenced pen. After exiting and entering the chuck (using /home and /back), one or two manage to appear outside the fence. Seems to be a more likely the higher the mod density.

**Comment by md-5** [comment]
This is a very old MC bug

**Comment by GenRedWolf** [comment]
OK. Seems to happen a lot this build, may just be the arrangement I made.

**Comment by md-5** [comment]
The bug happens more frequently the closer you are to the centre of the map - (0,0).
Since I believe I placed spawn at (0,0) that would likely be why.

EDIT: Spawn is at ~(80,256), but maybe that means your farm is pretty close to (0,0). I'd be nice if you could post the coordinates.

**Comment by MiniDigger** [comment]
this is the relevant Mojang issue https://bugs.mojang.com/browse/MC-2025
