### ISSUE TITLE
Breaking a stone axe causes achievement for diamond hoe.

### ISSUE THREAD

**Issue by DeusNinja** [SpigotMC/SpigotCraft#270]
http://prntscr.com/f5c6lf
I'm sorry in advance if this is not the proper way of going about this report, I was unable to test this in vanilla on the test server due to lack of effort as i'm probably just too drunk to do it right, but if that's the case, disregard this entirely. I hope I'm helping somehow, woot?! 

 .,But yeah, used up a stone axe on spigot test server, it told me dedication for challenge of depleting diamond hoe.

**Comment by Pokechu22** [comment]
Vanilla bug: [MC-117001](https://bugs.mojang.com/browse/MC-117001 "Serious dedication challenge is granted when breaking any tool")

**Comment by DeusNinja** [comment]
I can't figure out how to delete this issue D:
