### ISSUE TITLE
crafting white bed results in red bed

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#271]
If you craft a white bed out of white wool and wood planks, it becomes a red bed as soon as you place it in your inventory. In vanilla you get a white bed.

Edit: Take it out of the crafting table, place it in inventory - it stays white, take it again and place it in your tool bar slots - it becomes red.

**Comment by Pokechu22** [comment]
~I can't reproduce this.~

**Comment by Pokechu22** [comment]
Reproduced; it seems to happen whenever you move it in the inventory - if you change slots, or you drop it and pick it up again.  The recipe gives the right color, but the color data is lost in almost any other action.

**Comment by md-5** [comment]
Spigot aggressively updates item stacks, and has no way to tell the new white bed from an old red bed.

**Comment by Pokechu22** [comment]
Aggressively updating stacks shouldn't be needed - there's already a data fixer that updates old beds to new beds.  (It'll be needed for plugins creating beds, but I don't see why beds in the inventory would need to be updated once they've already been updated and the appropriate data version is the current one).

**Comment by md-5** [comment]
It's needed for CraftMeta and plugins using old data - check the current codebase for calls to convertStack.
In most cases this is fine because the old data is invalid, the new data is not. But in this case both the old and new data are valid.

**Comment by md-5** [comment]
Should be solved, thanks!
