### ISSUE TITLE
tamed sitting animals change position

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#272]
There was a tamed sitting wolf inside a building with an iron door at about 272 / 69 / -390
and a tamed sitting blue parrot inside its glass pane cage at 292 / 69 / -419.

Now they are at 279 / 68 / -404 (wolf) and 282 / 68.00 / -401 (parrot) sunken into farmland blocks.

First thought was vanilla bug MC-2025, but this lets entites only move into adjacent blocks. Animals who cross a fence can run away of course, but my animals were sitting.

I think this might have happened, when I got attacked at about the destination position by a skeleton (was outside my base behind the cobble wall). Getting attacked activates tamed animals (curiously tamed parrots too) to protect their owner. But that wouldn't have allowed them to leave their cages.

Maybe I teleported away (only ~15 blocks distance) with /home right at that moment.  So the animals might have lost track of me and got teleported to my (not the skeletons) last position with floored y?

I know, this is hard to reproduce, but at least I can prove the strange behaviour with the two wolf ears peeking out of the farmland. :)

**Comment by md-5** [comment]
I doubt this is our bug or a 1.12 bug.

**Comment by RunaMC** [comment]
Might have been [MC-96555](https://bugs.mojang.com/browse/MC-96555), fixed in 1.12 Pre-Release 1.
