### ISSUE TITLE
Players getting kicked on join

### ISSUE THREAD

**Issue by RoyalRaid** [SpigotMC/SpigotCraft#275]
Recently i've been having a issue where players are getting kicked on join with this msg. https://puu.sh/vMtkz/0819c0ba2c.png
Wondering if anyone can assist.
Thank in advance!

**Comment by Black-Hole** [comment]
Are you sure this happens on the Spigot snapshot server?

**Comment by md-5** [comment]
Considering it wasn't running Bungee at the time of this ticket, no.
