### ISSUE TITLE
Advancement "Postmortal"

### ISSUE THREAD

**Issue by Primorior** [SpigotMC/SpigotCraft#277]
Fly at a high that you would die, hold a totem of undying and change gamemode to 0, you won't get the advancement Postmortal for it. In vanilla it works (1.12-pre2)

**Comment by MiniDigger** [comment]
can reproduce, this is also true for other death reasons (tried drowning and getting killed by a spider)
the totem triggers but you don't get the advancement

**Comment by md-5** [comment]
The code is definitely there to trigger it

**Comment by md-5** [comment]
I did note the totem was not being consumed. After fixing that I definitely got the advancement.
