### ISSUE TITLE
Block Names not correct 1.11.2

### ISSUE THREAD

**Issue by smmmadden** [SpigotMC/SpigotCraft#278]
Hi, not sure if this is correct page for this, but I'm trying to create a QuickShop and sell blocks out of chests.  The problem comes up with some blocks not properly being registered with a user-friendly name and then the sign is confusing (e.g. STONE:1, LOG:2, etc).  From what I could find so far, the below is a list of blocks not shown in this page https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
and that is used for the plugin to identify one block over another in the config.yml below.  These names (first part) appear if I type /itemdb while holding the block.  However, when reloading the plugin with the changes below, I get "Invalid custom item name definition [X;X;X} Error: Invalid material: xxxxx  where the x's are the first UPPERCASED value.  Can someone help?
custom-items-name:
- NETHER_STALK;Nether Wart;Nether Wart
- GRANITE;Granite;Granite
- PGRANITE;PolishedGranite;Polished Granite
- DIORITE;Diorite;Diorite
- PDIORITE;PolishedDiorite;Polished Diorite
- ANDESITE;Andesite;Andesite
- PANDESITE;PolishedAndesite;Polished Andesite
- MCOBBLEWALL;MossCobbleWall;Mossy Cobble Wall
- DOAKSAPLING;DarkOakSapling;Dark Oak Sapling
- ACACIASAPLING;AcaciaSapling;Acacia Sapling
- PSAPLING;SpruceSapling;Spruce Sapling
- ACACIAPLANK;AcaciaPlank;Acacia Plank
- DOAKPLANK;DarkOakPlank;Dark Oak Plank
- SPLANK;SprucePlank;Spruce Plank
- ACACIALOG;AcaciaLog;Acacia Log
- DARKOAKLOG;DarkOakLog;Dark Oak Log
- SPRUCE;SpruceLog;Spruce Log

I'm using BungeeCord Server v1233, Spigot 1.11.2 (latest build) all on Windows 2010 Pro x64 O/S.
Thanks - Steve

**Comment by MiniDigger** [comment]
>  Hi, not sure if this is correct page for this

its not, use the forums, best place is the discussion section of the plugin. 
please close this issue, this bug tracker is for issues that come up while testing snapshot builds of spigot

**Comment by smmmadden** [comment]
thanks! Will do.
