### ISSUE TITLE
Grief

### ISSUE THREAD

**Issue by Legoman99573** [SpigotMC/SpigotCraft#285]
Seems someone was pissed and completely started griefing areas where there were builds at, but i have fixed as most as i can while taking a break from my own server. The only issue is that i cannot use logblock to tell who did it and report them. There might be some i missed as i dont remember some structures being there, but the ones i did remember, i have fully repaired them.

**Comment by MiniDigger** [comment]
if ppl want their stuff protected they can just claim the chunk.

**Comment by Legoman99573** [comment]
i see that, but lava, bedrock, and using random blocks to trash random areas does seem they covered whatever wasnt claimed

**Comment by sweepies** [comment]
You'll want to include the coordinates..

**Comment by Legoman99573** [comment]
![image](https://user-images.githubusercontent.com/7460704/27508810-fd7ebae8-58b2-11e7-9e03-943a30519f98.png)

around that area inside the rails that loop around the area

**Comment by Legoman99573** [comment]
Yeah, Scruffy allowed us to use lb lookup, so yeah. Hope you had fun Matthew_Cash. Scruffy undone your mess ;)

**Comment by ScruffyRules** [comment]
Fixed

**Comment by Legoman99573** [comment]
He did it again, and along with someone else. Decided to reopen this one instead of make a new one

![image](https://user-images.githubusercontent.com/7460704/27569803-2ae4cc76-5abf-11e7-8dfa-7a84cd9b5be2.png)

![image](https://user-images.githubusercontent.com/7460704/27569814-3e26017e-5abf-11e7-9547-44eccb936d74.png)

**Comment by ScruffyRules** [comment]
That was like 5 days ago, I reverted both users.

**Comment by ssamjh** [comment]
Rip why didn't I see this :O
