### ISSUE TITLE
Suggestion: Change /reload to something else

### ISSUE THREAD

**Issue by CandyCrystal** [SpigotMC/SpigotCraft#287]
Hello. When I updated my spigot server to 1.12, I ran into some issues with the /reload command, specifically that when I try to reload vanilla Minecraft functions and such, the server also tries to reload which causes massive lag spikes. so my suggestion is to change the /reload command to something else.

**Comment by MiniDigger** [comment]
You can use /minecraft:reload
Please note that this bug tracker isn't for the spigot software, just for the community server. 
Normally you should report bugs and suggestions here https://hub.spigotmc.org/jira

**Comment by md-5** [comment]
As above, use /minecraft:reload or override with commands.yml
