### ISSUE TITLE
Plot World Does Not Generate

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#292]
-

**Comment by md-5** [comment]
<MiniDigger>  md_5 https://github.com/MiniDigger/worldgentest <- source https://drive.google.com/file/d/1gPtcn6nh51zqeng8KD3f0gQEgUPS0u4E/view?usp=drivesdk <- jar https://i.imgur.com/tVYj60C.png <- expected result

**Comment by md-5** [comment]
WorldGeneration verified, need to check on multiworld support next

**Comment by MiniDigger** [comment]
@md-5, the worldgenplugin should have generated player heads, yet I don't see them on the 1.13 test world. they get generated on my 1.12.2 server (but the skulls don't have the proper texture, didn't have time yet to investigate that)

**Comment by md-5** [comment]
Yeah skulls are special and not yet implemented
