### ISSUE TITLE
potential chat sync issues? 

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/SpigotCraft#298]
two messages showed up in irc but not on my client:
![https://i.imgur.com/PLLiXzd.png](https://i.imgur.com/PLLiXzd.png)

**Comment by MiniDigger** [comment]
another instance
![https://i.imgur.com/6TMpzoD.png](https://i.imgur.com/6TMpzoD.png)

**Comment by md-5** [comment]
I feel like this is the result of plugins blocking spam, but the blocked message is going theough to irc.

**Comment by MiniDigger** [comment]
yeah, looks like it
![https://i.imgur.com/cE90nvb.png](https://i.imgur.com/cE90nvb.png)
the messages when thru to irc.
not sure if thats the case for the second message tho.
