### ISSUE TITLE
Unknown Command

### ISSUE THREAD

**Issue by wyatt-herkamp** [SpigotMC/SpigotCraft#299]
The Minecraft give command looks to be gone. Also few other commands look not to be in there? 
https://minecraft.gamepedia.com/1.13
However, it does look to be a vanilla bug.

**Comment by MiniDigger** [comment]
it doesn't show up in your suggestions because you don't have perm.
the unknown command message is a vanilla bug, (like "/give", "/give d" or "/give MiniDigger" in vanilla say unknown command too)
