### ISSUE TITLE
Investigate Tile Errors

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#314]
Lots of tile errors, seems the previous bed bug caused some, but now I'm seeing comparators as well

**Comment by TNTUP** [comment]
Not sure if those tile errors are related to Concrete Powder, when I place another one powder or a block it becomes into a solid concrete block

**Comment by md-5** [comment]
I think this is occuring when a plugin sets a legacy block we can't fully convert.
Seeing it for skulls a bit now also.

**Comment by TNTUP** [comment]
Seems not to be an issue for 17w50a, tested comparators and seems not bugged, they work now. But Concrete Power updates into a solid concrete without water, tile issue or thats a different issue?

**Comment by md-5** [comment]
Different issue

**Comment by md-5** [comment]
@TNTUP not seeing any issues with concrete powder. Can you please try and make a detailed bug report.

**Comment by md-5** [comment]
Confirmed reproduction - simply placing and then destroying a skull, saving the map, and restarting the server is enough to reproduce the issue.

I'm guessing the issue is missed or changed diff in the block place/break event snapshot handling

**Comment by md-5** [comment]
Quick diff review caught nothing, will need detailed investigation

**Comment by md-5** [comment]
Skulls are fixed seemingly due to some bad diff, but still trying to figure out the root cause of beds (and possibly others).

**Comment by md-5** [comment]
Vanilla bug

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-123432

**Comment by TNTUP** [comment]
So we'll see it probably fixed in 2018's snapshots or if we're lucky a last one in 2017 xD
