### ISSUE TITLE
Hide Bukkit Commands Without Permission from Client

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#317]

**Comment by md-5** [comment]
Solved for next release

**Comment by Pluginsel** [comment]
@md-5 I joined in SpigotCraft but isn't fixed yet. Is will fix soon?

**Comment by md-5** [comment]
Update hasn’t been released.
Also essentials and possibly other plugins don’t use bukkit permissions for command registration

**Comment by Pluginsel** [comment]
@md-5 is the update is out? if not, when is it will out?

**Comment by md-5** [comment]
This is out

**Comment by Pluginsel** [comment]
@md-5 How do we hide these visible plugin commands? Is there a similar setting in the Spigot.yml file:
`hide-plugin-commands: true`
or
`hide-insufficient-permission-commands: true`

**Comment by Black-Hole** [comment]
Actually Bukkit will query the permissions of every command it uses for the tab completion. But many plugins don't use the system and instead handle the permission check on it's own in the onCommand() method of the plugin or command handler.

For help "hiding" commands using "command hider" plugins please use the Spigot forums.
