### ISSUE TITLE
Kicked for spam without saying a word

### ISSUE THREAD

**Issue by ME1312** [SpigotMC/SpigotCraft#320]
Thought I'd let you guys know about this. I was testing the auto-completes and I happened to get kicked for spam without sending a single command/message. It's real easy to repeat too: just type in `/seen ` and then hold down the a letter/number button on the keyboard.

You can close this if that was your intention though.

**Comment by md-5** [comment]
1.12 behaviour, but probably needs tweaking if command completion is more "chatty"

**Comment by md-5** [comment]
Double the threshold of this for the next update
