### ISSUE TITLE
Concrete Powder block becomes solid if placing a block next to it

### ISSUE THREAD

**Issue by TNTUP** [SpigotMC/SpigotCraft#325]
Follow up #314 since this issue isn't related to tile entities.

To reproduce it:

Place one concrete powder and place another block next to the powder block it becomes into a solid concrete block. Tested inside of claim and outside. Not a vanilla issue in Single Player

**Comment by md-5** [comment]
Confirmed

**Comment by md-5** [comment]
Good find, fixed for next release

**Comment by TNTUP** [comment]
Noticed it while testing possible ideas xD Nice!

**Comment by md-5** [comment]
Deployed
