### ISSUE TITLE
Pumpkins turn into Carved Pumpkins

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#326]
When I take from the creative inventory a normal pumpkin and place it into my inventory it turns into a carved pumpkin. When I grow a pumpkin from seeds, it will grow an uncarved pumpkin, but when I mine it it will turn into a carved pumpkin as well.

**Comment by MiniDigger** [comment]
tested in vanilla, this definitely seems to be an spigot/craftbukkit issue as I could not reproduce it. You can successfully move a normal pumpkin into your hotbar from the creative inventory, without it turning into a carved pumpkin as it does on the spigot test server.

**Comment by md-5** [comment]
Probably need a conversion exception similar to what we have for beds in 1.12

**Comment by md-5** [comment]
Fixed for next release
