### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#328]
![2017-12-21_11 53 03](https://user-images.githubusercontent.com/13731539/34252867-93bed996-e645-11e7-81e3-79221828d82f.png)

**Comment by md-5** [comment]
Can you please explain

**Comment by MiniDigger** [comment]
I would guess he tried to build a cobble stone generator and it didn't work

**Comment by ghost** [comment]
Just checked it does this in vanilla as well, so not a Spigot issue.
