### ISSUE TITLE
Davallo gets kicked when joined

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#329]
He told me on his other account that he can't join the SpigotCraft server because he gets kicked for sending too many packets.

**Comment by ghost** [comment]
Let me correct his IGN is Davanno not Davallo.

**Comment by md-5** [comment]
Dont know how he set his position to NaN, so I've just deleted his data

**Comment by Pokechu22** [comment]
Might have teleported via [MC-121787](https://bugs.mojang.com/browse/MC-121787 "[MC-121787] Teleporting things to Infinity / NaN is possible"), though that would require weird timing.
