### ISSUE TITLE
Placing snow layer sets to full snow block

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#330]
Placing a snow layer on top of grass, places the first layer, then all the way up to a full snow block immediately.  

Doesn't behave this way on vanilla.

**Comment by klugemonkey** [comment]
Does this in the inventory as well.  Replacing single snow layer with full block.  But you can replace the inventory item and it puts in correct item image.

**Comment by klugemonkey** [comment]
Pulling grass into the quickslot also sets the item to full grass block.  Related to snow block.

**Comment by klugemonkey** [comment]
Both the naming conventions for grass and snow have changed, so therein lies the problem...

```
Old Name                New Name
-----------             ------------
grass                   grass_block
tallgrass               grass
double_plant:2          tall_grass

snow_layer              snow
snow                    snow_block
```

**Comment by md-5** [comment]
Same as #326

**Comment by md-5** [comment]
Thanks for the list - I've exempted both snow and grass.
Maybe we will need to be less aggressive in future, but probably best to stay as close to 1.12 as possible for now
