### ISSUE TITLE
wrong collision boxes (cobblestone wall, farmland, ...)

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#333]
I get stuck, when I run over farmland or along cobblestone walls. Maybe something is wrong with the collision/bounding boxes.

Does not happen with 17w50a in singleplayer.

**Comment by md-5** [comment]
Yeah it's nocheat+
I've disabled it here
https://github.com/SpigotMC/SpigotCraft/commit/e5f0d80282be2f117858d5a68ee2a6102b198376
