### ISSUE TITLE
durability bar invisible

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#335]
When I use tools like a stone pickaxe, the durability does not seem to wear off, because no durability bar appears. But suddenly the tools breaks. So the durability counting seems to work, but the durability bar is invisible.

Does not happen with 17w50a singleplayer or 17w50a vanilla multiplayer.

**Comment by md-5** [comment]
Confirmed

**Comment by md-5** [comment]
Good spot, actually a couple bugs at play here
