### ISSUE TITLE
strange behaviour of (wooden) doors

### ISSUE THREAD

**Issue by RunaMC** [SpigotMC/SpigotCraft#336]
If you place a wooden door (didn't test iron doors) right in front of another wooden door or two blocks in front of it, only the upper part of the door gets placed and it will vanish, when you click it. The door is not removed from your inventory.

You can place a wooden door **behind** a wooden door, but if you open the forward one, it will open and close immediately.

Both issues do not happen in 17w50a vanilla multiplayer.

**Comment by ScruffyRules** [comment]
Confirmed for 1.12.1 Vanilla, Craftbukkit, Spigot and 17w50a Vanilla
All multiplayer with spawn protection enabled.

**Comment by RunaMC** [comment]
I tested it in 17w50a vanilla singleplayer and multiplayer, both work fine.

I did some further investigation and here's a new observation:
A door seems to block the line of sight like a full block or maybe the collision boxes are mirrored/wrong facing. If you aim a door through the block of another door without the front door being actually in the way, the rear door will open but close immediately. The client seems to think it could open the door, but the server refuses it because it thinks, the front door would block the line of sight.

**Comment by ScruffyRules** [comment]
The reason was spawn protection for the doors behaving weirdly.

**Comment by RunaMC** [comment]
It still happens at -500/-500, far away from spawn.
If you stand inside the wooden door with the door in your back, you cannot interact with other blocks, cannot open doors or dig dirt.

**Comment by md-5** [comment]
We can’t reproduce this.
Can you try posting a video?

**Comment by RunaMC** [comment]
I am online currently. It also happens with slabs.

**Comment by md-5** [comment]
> If you stand inside the wooden door with the door in your back, you cannot interact with other blocks, cannot open doors or dig dirt.

It's NoCheat in this instance.
