### ISSUE TITLE
/execute in the_end run tp 0 100 0 fails

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#340]
Running /execute in the_end run tp 0 100 0 on a vanilla snapshot server will complete correctly, however on Spigot it will teleport you to the coords in your current world but not the correct dimension.

I have a feeling this may be because Essentials overwrites the /tp command.

I then attempted to run /execute in the_end run minecraft:tp 0 100 0, thinking that the minecraft:tp would assure it ran the vanilla command however I get
![error](https://puu.sh/yZyMe/117ce92144.png)

A way to fix this would be to allow the minecraft: commands in /execute.

**Comment by md-5** [comment]
Feel like 1.12.2 probably does this also.
Functions and stuff are a mess

**Comment by MiniDigger** [comment]
the execute-in-dimension stuff is something that was added in the 18w02a.

**Comment by md-5** [comment]
Fixed the command (without essentials).
Looking into tags

**Comment by md-5** [comment]
Yeah so /execute actually only runs Vanilla commands, which realistically is probably safer than the previous mismash.
Might keep it that way, dunno

**Comment by MiniDigger** [comment]
mmmh, while most options of the execute command are usless for bukkit commands (as bukkit commands don't have a location, rotation or dimension attached, unless you changed that in 1.13), but I can see /execute if/unless or /execute as come in handy. I would vote for the ability to execute bukkit commands.

**Comment by ssamjh** [comment]
I would also vote for /execute being able to execute bukkit commands.
It could be an addition in spigot.yml, allow-execute-bukkit-commands: true/false.

**Comment by md-5** [comment]
It's not trivial to redirect into bukkit commands

**Comment by Pokechu22** [comment]
> as bukkit commands don't have a location, rotation or dimension attached, unless you changed that in 1.13

Similarly they don't support selectors (which IMO is a bit of a flaw, but not much can be done about that at this point without breaking all the plugins).
