### ISSUE TITLE
Trident loyalty issues

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#345]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [X] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

The loyalty enchant for SpigotCraft seems to fail

Vanilla (creative): https://puu.sh/ztLWQ/bcb0b2803b.mp4

Spigot (creative): https://puu.sh/ztMbK/99d8fd3305.mp4

As a note, survival seems to work better.

**Comment by ssamjh** [comment]
Just tested on a high latency (200MS+, to replicate my ping to Spigotcraft) Vanilla server and it works as intended.

**Comment by md-5** [comment]
It's probably you throwing the trident beyond the entity activation range

**Comment by ssamjh** [comment]
What's the range for SpigotCraft?

**Comment by md-5** [comment]
Exempted for next release
