### ISSUE TITLE
Dear md_5 I broke something.

### ISSUE THREAD

**Issue by wyatt-herkamp** [SpigotMC/SpigotCraft#348]
Ok, the list of Online player when you hover over ping states KingTux is online. However I am not I am trying to join. Dinner Bone's MC Status states I am on too.
- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
I'm gonna pin this down to people using /locate and it crashing
