### ISSUE TITLE
Locate Command Crashing Server

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#350]
It looks like the locate command is locating structures by generating the entire world until it finds a structure.
This is clearly suboptimal compared to 1.12.

Need to check if this is a Vanilla thing

**Comment by 2008Choco** [comment]
Testing on a vanilla server yields no performance loss. Rather than infinitely generating the world, it returns with a message indicating that the structure could not be found nearby.

**Comment by Pluginsel** [comment]
Is lag for 2-3 seconds in Vanilla server, but is unimportant.
https://bugs.mojang.com/browse/MC-126244

**Comment by md-5** [comment]
It's working fine on my server too (without plugins though).
Needs further investigation.

**Comment by md-5** [comment]
<~md_5> Im thinking /locate is just an issue with the server being slow, maybe memory also?
<~md_5> I pulled exactly the same map and it completes in about 5 seconds on my pc

**Comment by md-5** [comment]
Server was running without Xmx flags, this meant it was defaulting to 1GB of ram.
/locate uses a lot of ram, so this was triggering a bunch of garbage collections, which meant that the locate could never complete. I've upped the ram, and locate is slow (see: vanilla ticket), but it does complete within a few seconds.

**Comment by Pluginsel** [comment]
@md-5 Yes, and my report is confirmed: https://bugs.mojang.com/browse/MC-126244
