### ISSUE TITLE
Elytra is broken

### ISSUE THREAD

**Issue by NicoNekoDev** [SpigotMC/SpigotCraft#351]
Flying down and up fast with elytra break the player possition and send wrong (invalid) data packets.
PS: I can't join the server unless my player file is deleted or I get offline teleported.
---

- [x] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by Pluginsel** [comment]
https://bugs.mojang.com/browse/MC-122354

**Comment by wouterdedroog** [comment]
Same.. http://prntscr.com/ilxvto Can someone delete my playerdata?

**Comment by md-5** [comment]
Whats your uuid?

**Comment by wouterdedroog** [comment]
836ce767-0e25-45a0-8012-fa1864d2b6aa

**Comment by md-5** [comment]
Removed, please don't use elytra until this is fixed
