### ISSUE TITLE
Trident enchants messed up

### ISSUE THREAD

**Issue by FrankHeijden** [SpigotMC/SpigotCraft#354]
SpigotCraft Issue Template
==========================
![2018-02-24_00 12 27](https://user-images.githubusercontent.com/22407829/36621296-8c7160de-18f7-11e8-9c4d-16ce5fd9dcc8.png)
all done using the anvil

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

---

- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
<~md_5> sigh
<~md_5> test on vanilla before opening an issue
<~md_5> this is why the checkboxes are there

**Comment by md-5** [comment]
Also

>Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.
