### ISSUE TITLE
Turtle Potion

### ISSUE THREAD

**Issue by wyatt-herkamp** [SpigotMC/SpigotCraft#355]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:
Whenever you add a  Turtle Potion to you inventory it turns to water potion
---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
<~md_5> sigh
<~md_5> test on vanilla before opening an issue
<~md_5> this is why the checkboxes are there

**Comment by wyatt-herkamp** [comment]
This does not happen in Vanilla.

**Comment by md-5** [comment]
Solved for next update

**Comment by wyatt-herkamp** [comment]
Awesome!
