### ISSUE TITLE
PlayerInfo TabList Player Name Length

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#357]
Only allows up to a length of 14 characters and splits player name.
![screenshot_3](https://user-images.githubusercontent.com/36784872/36626630-0e1385c8-192e-11e8-8269-16fed3a54b4b.png)

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot snapshot
- [ ] Bug does not exist on current Spigot snapshot

**Comment by md-5** [comment]
Essentials bug (feature?)
