### ISSUE TITLE
Fire charge interact

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#358]
When a player right-clicks a block with a fire charge it doesn't ignite the block. Not sure if it's something to do with the grief prevention plugin but if that was the case flint and steel interact would be cancelled as well.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Not a bug
