### ISSUE TITLE
Dispenser Fire charge

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#359]
When a fire charge projectile launches from a dispenser isn't meant to ignite the target block. Probably something to do with the grief prevention plugin again...

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
I just tested this on single player, and the block ignites. Not a bug.
