### ISSUE TITLE
Does HeroChat work with PurpleIRC?

### ISSUE THREAD

**Issue by RoboMWM** [SpigotMC/SpigotCraft#36]
I'm not sure how this will play out with PurpleIRC, if we will be using in-game channels. Then again, I've hardly touched HeroChat so I'm not sure.

**Comment by HappyHarm** [comment]
I googled a bit and saw some descriptions from updates from PurpleIrc are based on HeroChat. So yes I think they support eachother.

**Comment by RoboMWM** [comment]
Ok I see, so it can work in specific channels or not. If we even create channels. People then should be adjusting chat formatting in HeroChat instead of Essentials then I'd believe.
