### ISSUE TITLE
Dispenser Experience Bottle

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#360]
When activating a dispenser with Experience Bottles inside non do not shoot and non are removed from the dispenser.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Can't even reproduce this on SpigotCraft
