### ISSUE TITLE
Map focusing on other player

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#362]
When you rejoin the server after creating a new map and another player is on the server as well the map focuses on a different player rather than yourself.

Demonstration:
https://youtu.be/rulg7569tAo

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Maybe same as fix for #361, need someone to check

**Comment by md-5** [comment]
It looks like the issue here is that all maps being created are ID 0
