### ISSUE TITLE
Inventory Updating - Block Place

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#363]
I wasn't going to report this because I'm sure you've been told about this bug many times as it appears in previous versions but what the hell. When placing a block in survival mode when the event is cancelled, the player loses the item they placed however if they click on the slot where the item was in their hotbar previously or move an item to the slot the item they placed from their hotbar was previously the item reappears. I'd suggest updating the players inventory after the event is cancelled or setting the item to their hotbar slot (might not help because the player would most likely have a duplicate of the item) while checking if the player's game mode is survival.

- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Cannot reproduce on either 1.12.2 or 18w08b

Code:
```
    @EventHandler
    public void test(BlockPlaceEvent e)
    {
        e.setCancelled( true );
}
```
