### ISSUE TITLE
Item Frames and Paintings don't despawn when you destroy the block they are placed on

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#364]
Demonstration:
https://youtu.be/GacK4p_RApo

When shooting a projectile in creative mode they despawn and when shooting a projectile in survival mode they despawn and drop which is fine.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Looks to be a plugin

**Comment by md-5** [comment]
Looks like a non optional thing in griefprevention:
https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L556

A config would be nice @RoboMWM

**Comment by xXSeikoStormXx** [comment]
hello players can break blocks in my server MC.SeikoCraft.Com.
and I have claimed spawn with Grief Prevention.
but it doesn't claim all the blocks just some of them in 1.14.4
make sure you fix the problem with blocks.
