### ISSUE TITLE
Shulker Box occasionally drops when putting no items into the inventory

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#367]
When destroying a shulker box after placing it the shulker box including not putting any items into its inventory, the shulker box drops with an NBT tag (not visible).

Demonstration:
https://youtu.be/cLMX5QaxrgE

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
I really don't think this is an issue, but it's not a new bug in the snapshot anyway
