### ISSUE TITLE
Shulker Box - Items Remain

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#368]
When you place a shulker box at a location and put items into the inventory then destroy the shulker box and place a new one at the same location. you find the items you put in the other shulker box appear in the new shulker box.

Demonstration:
https://youtu.be/crwuCCvftCU

This may relate to my previous report.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version
- [ ] Bug does not exist on current Spigot version

**Comment by ghost** [comment]
Even rejoining and then placing a shulker box at the same location still has the items I put into the shulker box when I cleared my inventory and put a new shulker box in my hotbar. Maybe stored within my playerdata.

**Comment by md-5** [comment]
Relates to https://bugs.mojang.com/browse/MC-123432

**Comment by md-5** [comment]
Fixed for next release
