### ISSUE TITLE
Map doesn't focus on other players

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#370]
When you use a map you can see a pinpoint of yourself which follows you as you move but when you give the map to another player and they give it back to you, when you look at the map you cannot see that players pinpoint moving when they move around.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot snapshot
- [ ] Bug does not exist on current Spigot snapshot

**Comment by md-5** [comment]
Please stop ticking current spigot version unless you mean 1.12.2
Does this exist on 1.12.2 or not?

**Comment by ghost** [comment]
Not 1.12.2. The snapshot version.

**Comment by ghost** [comment]
Demonstration:
https://youtu.be/WyPg5ig4NGs

There's one problem with vanilla snapshot and two problems with the spigot snapshot as shown in the video.

**Comment by md-5** [comment]
Not sure about your setup in the second video (were you perhaps using a lan server?)
But I just replicated it in the vanilla server.
I'm not sure what you mean by "two problems", there's only one described in this ticket.

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-126350

**Comment by ghost** [comment]
I was using vanilla server.

On the spigot test server when I give a player my map they can see their pinpoint following them as they move but when the player that gave them the map moves you don't see their pinpoint following them on the map. If I were to give the player back the map and the player that gave it to me moves their pinpoint doesn't follow them but if the player that now has the map moves the pinpoint follows them. Both are a bug.

But on the vanilla server I setup, when I give a player my map they can see their pinpoint following them as they move same with the player that gave them the map which isn't a bug. However, If I were to give the player back the map and the player that gave it to me moves their pinpoint doesn't follow them but if the player that now has the map moves the pinpoint follows them which is a bug.

**Comment by md-5** [comment]
I'm finding it really hard to understand your phrasing, but on my vanilla server the maps never have more than one icon being able to move at a time. The icon which moves is the icon corresponding to whoever is currently holding the map.

This is the same behaviour as Spigot

**Comment by ghost** [comment]
Not sure then sorry. You'd have to take a look at the video again if you want to understand better because I'm confused also.

**Comment by md-5** [comment]
I don't know why your vanilla server works in the first instance, but mine doesn't, so as far as I'm concerned this is a 100% vanilla bug.

**Comment by ghost** [comment]
Yeah. After going over it again but I'm still confused with this bug as it doesn't occur on the vanilla server. Whereas the other bug occurs on both.
![image](https://user-images.githubusercontent.com/36784872/36639966-05ddd318-1a0f-11e8-869d-49e895b1d20d.png)

**Comment by md-5** [comment]
It occurs on my vanilla server, the only player tracked is the one currently holding the map

**Comment by ghost** [comment]
But on the vanilla server the player is tracked at this point of the video https://youtu.be/WyPg5ig4NGs?t=1m5s

**Comment by md-5** [comment]
Emphasis on *my* vanilla server

**Comment by ghost** [comment]
Could you show your outcome?

**Comment by md-5** [comment]
It's exactly the same as your spigot video, but on vanilla.
Just tested it again after a server restart with a new map item, same thing, only the player holding the map is tracked.
This is a 100% vanilla issue in my eyes, maybe it requires specific circumstances that aren't being replicated exactly on your Vanilla setup, but it is on mine and I don't see any reason to look at this further

**Comment by ghost** [comment]
Okay, thanks. Appreciate your response.
