### ISSUE TITLE
Q&A : How to fix the multiplayer crash?

### ISSUE THREAD

**Issue by Pluginsel** [SpigotMC/SpigotCraft#372]
Question: How to fix the multiplayer crash with no need to join the singleplayer world?
Answer: Update the server to 18w09a. :)

**Comment by wyatt-herkamp** [comment]
I bet @md-5 is working on this. So don't rush him or he might create a big bug.

**Comment by MiniDigger** [comment]
@Pluginsel you do realize that its not as easy to drop in a new jar and call it a day? 
spigot needs to be updated to that new version, fixing stuff like new mapping, newly introduced bugs etc. 
this takes time. also, md might have different stuff to do right now. like, he is not even awake yet.   
you will be notified when the server has been updated via the forums.

**Comment by mrfloris** [comment]
@MiniDigger I've already told him that twice on the forums where he also pushed for it.
