### ISSUE TITLE
@MD_5

### ISSUE THREAD

**Issue by Pluginsel** [SpigotMC/SpigotCraft#375]
Hello,
The SpigotCraft server does not attract as many players as before. And when you open the door, many people did not enter the server because they were crashing, so there were those who could not get into the server.
Anyway, now I see that the crash has been resolved in 18W09A, so can you open a new topic? So make that server live again.

**Comment by MiniDigger** [comment]
You do realize that the more issues you create wanting him to update the server the more time he needs to take closing them and not working on updating spigot, right?
This server is about testing release critical bugs of new spigot versions. Once md is done updating spigot he will reply to the forum post and ppl can continue testing.
Please refrain from creating any further issues if you don't want to report an actual bug.
