### ISSUE TITLE
No (or very few) fishes spawning

### ISSUE THREAD

**Issue by wouterdedroog** [SpigotMC/SpigotCraft#376]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [X] Bug does not exist on current Spigot version (1.12.2)

I was flying around in the map, and I noticed that there weren't any natural fishes.. I visited multiple biomes, I found 1 fish..

The testing I did happened around -3701, 64, 447, which is not very close to the spawn.

So, my bug is:
- Almost no natural fish spawns.

**Comment by masterdoctor** [comment]
Possible reason: Spigot has spawn caps for each mob (I can't recall if they're enabled by default) but it would mean that if the fish entities haven't been added the values will default to 0 (using the Bukkit/Spigot FileConfiguration class).

**Comment by md-5** [comment]
I don't think there is any reason why fish would have a spawn rate any different to what is globally applied / applied to other animals

**Comment by Cr-aft** [comment]
I'm 99% sure Fish Spawn Depending Squid Spawn.
What that means is if spigot limit's squid spawns in any way that you will see far less fish spawning in the area. MC basis's it on if there is enough water, squids in the area to spawn fish. Squids have very limited needs to spawn so shouldn't be a major issue but if there is a max squid spawn or something could be why?

**Comment by md-5** [comment]
I also think they only spawn in oceans, potentially even specific oceans.
I'm trying to find an ocean on my map(s) now

**Comment by Cr-aft** [comment]
Yes.
Cold Biomes have Specific Fish,
Warm Biomes have Specific Warm biome fish (puffer fish etc).
I Think Salmon are only ones to spawn in rivers.

Also i did finally find a fish BUT thats only because 1 Squid finally spawned allowing for 1 Cod to spawn.

![2018-03-04_20 32 17](https://user-images.githubusercontent.com/37057172/36956453-b3d2def0-1feb-11e8-8f6c-63cc6c1da574.png)
![2018-03-04_20 32 07](https://user-images.githubusercontent.com/37057172/36956467-c3a6a23a-1feb-11e8-88cb-81dca456d77a.png)

**Comment by md-5** [comment]
Should be improved for next release
