### ISSUE TITLE
Parrot's Turn Invisible WHEN they Land on your Shoulder + they play Incorrect sounds randomly

### ISSUE THREAD

**Issue by Cr-aft** [SpigotMC/SpigotCraft#378]
SpigotCraft Issue Template
==========================

- Parrots Turn Invisible once they land on your shoulder this never happened in 1.12.2 spigot.

Another thing is Parrots Make RANDOM noises instead of properly mimicking mobs around you like they use to. The Main bug here is them turning invisible on a players shoulder.

**Comment by md-5** [comment]
You didn't follow the template.
What about Vanilla?

**Comment by md-5** [comment]
Vanilla bug

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-124114

**Comment by Cr-aft** [comment]
So Sorry MD-5 I should have checked vanilla first. I was going to but jumped the gun. Sorry for wasting your time.

**Comment by md-5** [comment]
Don't worry, I'll leave this open so others can track
