### ISSUE TITLE
Server Crashes on connect (unique to me)

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#380]
Hey there just a unique issue to me, can test if needed, but resetting playerdata should work.

UUID: f723cefa-bb36-43c8-a123-015b2b58e4d7

I logged in, warped to aquatic, and then ran /locate Ocean_Monument (or ruin) and teleported to it.
The server then promptly shutdown and when I connect it crashes again.

**Comment by md-5** [comment]
No, there's some serious issues with world gen that need resolving

**Comment by md-5** [comment]
Should be fixed assuming plugins don't hate the changes I had to make
