### ISSUE TITLE
Getting Treasure map Disconnects with Internal Server Error

### ISSUE THREAD

**Issue by Legoman99573** [SpigotMC/SpigotCraft#382]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [x] Bug does not exist on current Spigot version (1.12.2)

So when you go to any chest that has a treasure map in it and show it, it disconnects you and you can no longer rejoin the server with this message:
![image](https://user-images.githubusercontent.com/7460704/37555762-aaeff916-29ba-11e8-8a45-0e6752fb6431.png)

**Comment by md-5** [comment]
Easiest way to get one?

**Comment by Legoman99573** [comment]
Shipwrecks is where I was at last before I had the issue
