### ISSUE TITLE
Fished stuff don't "jump" correctly to the player position

### ISSUE THREAD

**Issue by Zurishadai** [SpigotMC/SpigotCraft#383]
- [X] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

Go fishing and you will see fished stuff don't appear as before, near the player position.

**Comment by md-5** [comment]
Same deal, please consider reporting to Mojang and linking here
