### ISSUE TITLE
Filling bucket with water/lava, except when using a dispenser, make the bucket dissapear

### ISSUE THREAD

**Issue by Zurishadai** [SpigotMC/SpigotCraft#384]
- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

Basically the title: you fill a bucket with water/lava and it dissapears miliseconds after filling it.

**Comment by md-5** [comment]
Should be solved
