### ISSUE TITLE
2 normal chests don't make a big one instantly

### ISSUE THREAD

**Issue by Zurishadai** [SpigotMC/SpigotCraft#385]
- [X] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

Put 2 chests quickly, one next to another and you will see they don't inmediately "fusion" so you have to break it and put it again in order to work as normally does.

**Comment by md-5** [comment]
Please report to bugs.mojang.com if you can
