### ISSUE TITLE
Sugar cane can be placed on water

### ISSUE THREAD

**Issue by Zurishadai** [SpigotMC/SpigotCraft#390]
- [x] Bug does not exist on current Vanilla snapshot
- [X] Bug does not exist on current Spigot version (1.12.2)

![image](https://user-images.githubusercontent.com/37492454/37697888-322ee678-2ce8-11e8-95e7-9f7a366c0fa2.png)

**Comment by md-5** [comment]
I can reproduce this on single player vanilla.

Please report to the Mojang issue tracker (after searching for a duplicate)

**Comment by md-5** [comment]
![2018-03-21_20 32 09](https://user-images.githubusercontent.com/1007849/37702543-fdc4fb20-2d46-11e8-82bb-1e32b0f09a3a.png)

**Comment by Zurishadai** [comment]
I tried to reproduce it but I couldn't. Now I double check in Vanilla and Spigot. 

The other Mojang bugs I have reported them here because I thought it was necessary due having the option to mark if they were vanilla or not.
Do you understand me?

**Comment by md-5** [comment]
You need to have it be on the edge of a layer for the bug to happen.
If I have tagged the bug as Vanilla it is ok for you to report to bugs.mojang.com

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-127533
