### ISSUE TITLE
Trident Duplication

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#394]
https://hub.spigotmc.org/jira/browse/SPIGOT-3919

So, I was playing on SpigotCraft (play.spigotmc.org) and I was trying out the new trident that I have just found. I was throwing it just for fun, to see how it works, then I had an idea to take trident into my left hand, hold the right mouse button to prepare it for the throw, and almost at the same time I pressed F key again, to place trident back to my right hand. So the trident flew out as it should, but at the same time, I still had that trident in my inventory, so I was able to pick that thrown trident up. So that was how I discovered the way to duplicate tridents. It also works with enchants, and on a multiplayer server.

Instead of an image, I uploaded a video of this bug.
https://youtu.be/ygZsdKfoNt4

**Comment by md-5** [comment]
Needs checking, especially on Vanilla

**Comment by Pokechu22** [comment]
~~This is a vanilla issue, will look for the ticket...~~ nope, I saw someone report the spigot issue on the vanilla tracker with that same text: https://bugs.mojang.com/browse/MC-129093
