### ISSUE TITLE
Furnace cooking fuel use laggy/buggy

### ISSUE THREAD

**Issue by SebRomu** [SpigotMC/SpigotCraft#396]
When cooking/smelting items in furnace it seems to lag (might be unrelated) and sometimes uses one more fuel than required if additional fuel is in the furnace, or requires more fuel than expected.  
  
Tested in Spigot Community snapshot server:

One iron ore and three sticks should leave one stick, but the last stick will be consumed, and burn away in an empty furnace.

Also if exactly the expected fuel needs, the last item sometimes fails to cook/smelt fully.

Put 16 iron ore in furnace with 2 coal, last iron ore failed to produce iron ingot, when furnace stopped burning.

Expected normal fuel to smelt/cook ratios.
---

- [ ] Bug exists on current Vanilla snapshot (18w20c)
- [ x] Bug does not exist on current Vanilla snapshot (18w20c)
- [ ] Bug exists on current Spigot version (1.12.2)
- [ x] Bug does not exist on current Spigot version (1.12.2)

**Comment by md-5** [comment]
I can't reproduce either of these.
