### ISSUE TITLE
Server Crashing [When Players Join] Server stopped Responding

### ISSUE THREAD

**Issue by HN-ERP** [SpigotMC/SpigotCraft#397]
https://pastebin.com/6pkpkBdx
I'm having this problem when Everytime someone  joins to server or i reset the World Folder. My server decides to crash on me and i get the report what i have posted above?
If anyone can help me that would mean a lot!

**Comment by Black-Hole** [comment]
This bugtracker is for the testserver for the 1.13 snapshots.

Anyway, 1.8.8 isn't supported for over 3 years now, please update to 1.12.2 and use the Spigot bugtracker them.

**Comment by HN-ERP** [comment]
I ent changing my server from 1.8.8 to 1.12 its a factions server not a hypixel

**Comment by Black-Hole** [comment]
Factions does support 1.12.2: https://www.spigotmc.org/resources/factions.1900/

For help updating your server and your plugins please use the community support of the Spigot forums.
