### ISSUE TITLE
Spigot Server ignores --date-format parameter

### ISSUE THREAD

**Issue by fwillo** [SpigotMC/SpigotCraft#398]
Dear All, 

I reentered the SpigotServer after long time. After some use I wanted to customize the Date output in the console. For this the server offers the --date-format paramerter in use with Javas SimpleDateFormat ([https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html](https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html)) as advertised here [https://www.spigotmc.org/wiki/start-up-parameters/](https://www.spigotmc.org/wiki/start-up-parameters/). I try to run the server with: 
`java -jar spigot-1.12.2.jar --date-format "yyyy-MM-dd HH:mm:ss"`

I always get the time in the standard format (HH:mm:ss). It seems like the program is ignoring the parameter? Or is the information regarding the startup parameters not updated? This was encountered with the current stable release 1.12.2 and 1.12.1.

- [ ? ] Bug exists on current Vanilla snapshot
- [ ? ] Bug does not exist on current Vanilla snapshot
- [ ✔ ] Bug exists on current Spigot version (1.12.2)
- [ × ] Bug does not exist on current Spigot version (1.12.2)

**Comment by Black-Hole** [comment]
Please note that this bug tracker is for the test server for 1.13 snapshots.
The issues tracker for Spigot is at https://hub.spigotmc.org/jira

Anyway, I think this parameter won't work anymore because Minecraft changed logging to Log4J some years ago. Maybe you'll find some information on custom Log4J config on the Spigot forums.

**Comment by fwillo** [comment]
Oh sorry, I thought this was the proper git repo. Thanks for the hint with Log4J. I'll take a look. A possibility to modify this behaviour with a start-up parameter might be a convenient solution for the future though!

**Comment by md-5** [comment]
Sorry there won't be a startup param, all logging config is unified via log4j
