### ISSUE TITLE
Essentials GC Command Shows Error

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#402]
Title

**Comment by wyatt-herkamp** [comment]
Bad, @md-5 you didn't provide any errors or anything.

**Comment by md-5** [comment]
This works even on my test server.
Maybe SpigotCraft is not up to date. I forgot what https://github.com/SpigotMC/SpigotCraft/commit/328337a092f650aca560f32646f86bad0a7e1e3b was even for

**Comment by md-5** [comment]
<~md_5> something to do with banner tiles
<~md_5> they moved banner colours out of the nbt
<~md_5> but the blockstate system is a pure NBT snapshot
