### ISSUE TITLE
Treasure Map Rendering & Game Kicks

### ISSUE THREAD

**Issue by MagiskSec** [SpigotMC/SpigotCraft#405]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [x] Bug does not exist on current Spigot version (1.12.2)
------------------------------------------------------------------------------

There seems to be some issues with explorer maps.

1 - Instead of them actually loading map data on the map when they are opened close to the location of the buried treasure, it shows grey instead (sometimes odd bits patch through but mostly is just a grey colour).

2 - It seems that chests with maps in kick me from the server (https://i.imgur.com/Olt546J.png). I have a chest with maps I had discovered in and whenever I open I get this message, and as I was putting an opened map in to a chest I seem to have got the same kick message. (The chest I put this map in now also will not open.)

This does not appear on vanilla for me, if you want to see for yourself on the server it is in the Aquatic world co-ords (-225, 64, 336) and the bugged chests have signs on them.

**Comment by md-5** [comment]
>1 - Instead of them actually loading map data on the map when they are opened close to the location of the buried treasure, it shows grey instead (sometimes odd bits patch through but mostly is just a grey colour).

This is definitely a vanilla bug.
https://bugs.mojang.com/browse/MC-129623

**Comment by MagiskSec** [comment]
Ah sorry, I'd tested it on my own and I wasn't recieving it... my bad.

**Comment by ssamjh** [comment]
The issue is not happening with single player or on Vanilla servers.

Breaking a "glitched" chest on SpigotCraft will disallow you from joining: https://i.imgur.com/My4xxT5.png

What is in the "glitched" chest: https://youtu.be/scyUMpEEgO0

**Comment by md-5** [comment]
<~md_5> the map was never converted properly
<~md_5> its likely a case of mojang missed a conversion and only added it in after the conversion had already run
<~md_5> I dont think its wowrth looking into further at this point, as I said snapshot->snapshot updates arent actually supported

**Comment by md-5** [comment]
I will make sure to test custom display names converting from 1.12 though
