### ISSUE TITLE
Got a error the Minecraft server it not respoding

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#407]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

will the Minecraft server on spigot 1.12.2 for it stopped responding here the link for it the error https://pastebin.com/HUbtin5v

---
- [x] Bug exists on current Spigot version (1.12.2)

**Comment by md-5** [comment]
Use the forums for support.
You have an incompatible essentials version installed.
