### ISSUE TITLE
Are we using Essentials for ban/kick management?

### ISSUE THREAD

**Issue by ctian1** [SpigotMC/SpigotCraft#41]

**Comment by Nebhay** [comment]
We could use MaxBans as i have used that in the past for ban/kick management

But I still think we should use Essentials for this

**Comment by JamieSinn** [comment]
Essentials is just easier to use :+1:

**Comment by Cldfire** [comment]
Essentials :+1:

**Comment by Ichbinjoe** [comment]
Why complicate things? Essentials works for 95% of use cases. :+1: essentials.

**Comment by RoboMWM** [comment]
Considering this isn't a permanent server, even vanilla commands should suffice. Anything else is more for ban tracking and formatting (or so it seems to me).

**Comment by HappyHarm** [comment]
:+1: Most ban systems have an import function for Essentials so essentials is good to use/start with.
