### ISSUE TITLE
[Spigot Watchdog Thread/ERROR]: The server has stopped responding!

### ISSUE THREAD

**Issue by Milkshake777** [SpigotMC/SpigotCraft#410]
here is it
https://gist.github.com/Milkshake777/a95c187a2a6bf25bc594084447f5ed87
- [x] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

**Comment by md-5** [comment]
1) This is not a support site
2) Your server is outdated
3) Obvious plugin issue is obvious
