### ISSUE TITLE
Bug breaking trees and ores

### ISSUE THREAD

**Issue by leonardo-dgs** [SpigotMC/SpigotCraft#411]
Sometimes, when you are chopping trees or mining ores, other attached blocks get instantly broken

---

- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [x] Bug does not exist on current Spigot version (1.12.2)

**Comment by Pokechu22** [comment]
The server has the VeinMiner plugin installed; I suspect that this is that plugin (however, I don't know how it works exactly).

**Comment by md-5** [comment]
Sometimes = when sneaking :p
