### ISSUE TITLE
When I join the server I got kicked and get an error

### ISSUE THREAD

**Issue by leonardo-dgs** [SpigotMC/SpigotCraft#412]
When I join the server I instantly got kicked and this error;
https://imgur.com/a/2vIm4sG

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [x] Bug does not exist on current Spigot version (1.12.2)

**Comment by md-5** [comment]
Yes, there's some bad items in the world.
I think they're from broken snapshot->snapshot upgrades
