### ISSUE TITLE
Server closes because of an armor dispenser

### ISSUE THREAD

**Issue by Mario359** [SpigotMC/SpigotCraft#413]
Here is a video: https://youtu.be/aLaEj6eAtSo
Tested: 28/06/2018 ~12:40 (FR)
Maybe the server created an error

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [x] Bug does not exist on current Spigot version (1.12.2)

**Comment by md-5** [comment]
Huh this isn't crashing my test server.
There's something else going on, but not sure what

**Comment by md-5** [comment]
Oh, it's only when you stand right in front of the dispenser

**Comment by md-5** [comment]
Good find!
