### ISSUE TITLE
Duplication with an armor dispenser

### ISSUE THREAD

**Issue by Mario359** [SpigotMC/SpigotCraft#414]
Here is a video: https://youtu.be/1gSB_yTb9cY
I do not know if this bug comes from Spigot or a plugin
It can be Essentials, WorldEdit or WorldGuard

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

**Comment by MartenM** [comment]
**Some side-notes:**
- Bug only occurs when the armor piece is dispensed into the armor slot.
- Bug does not occur on a clean 1.12.2 server.

**Comment by md-5** [comment]
Thanks for the report!
Probably won't get a chance to fix this till next week.

**Comment by md-5** [comment]
Yeah I see this
