### ISSUE TITLE
Merged chorus fruits dont show as multiple when breaking plant

### ISSUE THREAD

**Issue by ssamjh** [SpigotMC/SpigotCraft#415]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:

---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [X] Bug does not exist on current Spigot version (1.12.2)

Best explained in this video: https://youtu.be/subwPwgs4AI

This issue could be a problem with all stacking but try as I might, I can't get TNT to work :(

**Comment by md-5** [comment]
I watched the video and I still don’t get it.

**Comment by ssamjh** [comment]
The chorus fruit items are stacked on the ground but appear as one singular item.

When the items are merging into one stack it works, but on the ground, it looks like there's only one chorus fruit on the ground itself.

Hope that is a little easier to understand.

**Comment by md-5** [comment]
Right I think I see now.
Not sure how this could be our fault but I’ll take a look when I can

**Comment by ssamjh** [comment]
Yeah, it's super low priority.

**Comment by YourMCGeek** [comment]
Call me crazy but there are three items here in a stack of 19 I believe it was? 
![Image](http://yourmcgeek.ga/u/21.05.21-17.01.19.png)

**Comment by ssamjh** [comment]
I will check it out later.

**Comment by md-5** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-4591
