### ISSUE TITLE
Can't join anymore - remove map items

### ISSUE THREAD

**Issue by AlexDicy** [SpigotMC/SpigotCraft#416]
This is related to the issue #405 I've taken a buried treasure map from a chest and put it in my inventory, this resulted in an instant crash and I can't join the server anymore.

It would be awesome if you remove this map from my inventory (editing the uuid.dat file or using a plugin)

Username: `HAlexTM`
UUID: `2af8c25e-0f0c-4a55-9b92-6fd5a98e07a8`

**Comment by AlexDicy** [comment]
Thanks a lot md_5, even though I have nothing left in my inventory, I had enchanted stuff, I guess I'll need to make them again

**Comment by AlexDicy** [comment]
Used the command `/rtp` and got to a village, someone has already been there, I've found a chest that had pants with mending and decided to empty the chest, worth nothing that one of the items was a map and was already written, made me crash again. Sorry for bothering

**Comment by md-5** [comment]
Done.
Please leave the maps alone.
I think its time for a world reset

**Comment by AlexDicy** [comment]
Agreed, a fresh restart is needed to both the nether and the overworld
