### ISSUE TITLE
tab-complete: -1 option in spigot.yml does nothing

### ISSUE THREAD

**Issue by DoNotSpamPls** [SpigotMC/SpigotCraft#417]
- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [X] Bug does not exist on current Spigot version (1.12.2)

Self-explanatory, tab completion still works perfectly even when disabled.

**Comment by md-5** [comment]
This is not the spigot bug tracker
