### ISSUE TITLE
Shield blocking mobs doesn’t make sound

### ISSUE THREAD

**Issue by bs** [SpigotMC/SpigotCraft#422]
When blocking a mob’s attack with the shield, no sound is played at all.
---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [X] Bug exists on current Spigot version (1.12.2)
- [ ] Bug does not exist on current Spigot version (1.12.2)

**Comment by md-5** [comment]
It's because of this silly thing https://www.spigotmc.org/threads/stripping-down-entitydamageevent-damagemodifier.194446/

**Comment by bs** [comment]
Wow, amazing that the debate has gone on for so long! Chances of the API actually getting removed?
