### ISSUE TITLE
Bed (Half placement)

### ISSUE THREAD

**Issue by ShaneBeee** [SpigotMC/SpigotCraft#424]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [x] Bug does not exist on current Spigot version (1.13.2)

When placing a bed only half of the bed places. 
If you place another bed where the missing part should be, the whole bed connects

Proof
![](https://i.imgur.com/kkAakCL.png)

**Comment by md-5** [comment]
Visual issue, a relog shows the whole bed

**Comment by ShaneBeee** [comment]
Hmm.... that is odd

**Comment by ShaneBeee** [comment]
Im curious though, if this is a client side issue, why does it not happen on a vanilla server?

**Comment by md-5** [comment]
It is a server issue

**Comment by ShaneBeee** [comment]
oh gotcha,
