### ISSUE TITLE
Bell sound

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#428]
When right-clicking a bell at the spawn there's no bell sound.
==========================
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)

**Comment by md-5** [comment]
Spawn protection.....

**Comment by ghost** [comment]
I cannot replicate this on vanilla snapshot in spawn protection.

**Comment by ghost** [comment]
The bell is moving too.

**Comment by md-5** [comment]
>I cannot replicate this on vanilla snapshot in spawn protection.

I just did.

Perhaps you were op or outside spawn protection.

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-142635

**Comment by ghost** [comment]
> https://bugs.mojang.com/browse/MC-142635

Thanks
