### ISSUE TITLE
Fire Charge not igniting

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#432]
When right-clicking a block with a fire change the block doesn't ignite.
==========================

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)

**Comment by md-5** [comment]
Looks to be a permission and/or plugin thing.

**Comment by md-5** [comment]
Looks to be griefprevention

**Comment by md-5** [comment]
GriefPrevention hardcodes only allow flint and steel if firespreads is false...

https://github.com/TechFortress/GriefPrevention/blob/9ff369fd62991480a3880dce81d0a302a3f5437c/src/main/java/me/ryanhamshire/GriefPrevention/BlockEventHandler.java#L640
