### ISSUE TITLE
Exploring locked map

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#434]
You can explore a locked map.
==========================

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)

**Comment by md-5** [comment]
Can you please provide more info than 1 line

**Comment by ghost** [comment]
When you have a locked map that shows an area that has not been explored yet (top left)
![image](https://user-images.githubusercontent.com/36784872/51376247-c8d69700-1aff-11e9-8bcb-4c61077845c4.png)
Then you move towards the unexplored area. The area becomes explored when it shouldn't be.
![image](https://user-images.githubusercontent.com/36784872/51376347-03d8ca80-1b00-11e9-9e40-39aa4fa8df25.png)

**Comment by md-5** [comment]
How can you tell the map is locked?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36784872/51376535-79449b00-1b00-11e9-963d-42c83105cd64.png)

**Comment by md-5** [comment]
ty

**Comment by md-5** [comment]
Not a bug, just #433 showing maps and locked when theyre not really
