### ISSUE TITLE
Scaffolding placement problems in spawn protection

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#444]
When placing a scaffolding onto another scaffolding inside the spawn protection, the block remains for the player placing it until the chunk unloads or player disconnects from the server. The item is also removed from the players inventory until they click onto the slot with the item or reconnect to the server.

- [x] Bug exists on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)

**Comment by ShaneBeee** [comment]
1) Why are you changing the template?
The template is as follows
```
- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [ ] Bug does not exist on current Spigot version (1.13.2)
```
This is asking if it does or does not happen in vanilla.
And then its asking if it does or does not happen in the current release (being 1.13.2)
The point of this is so md_5 can rule out of this is an issue with Vanilla or an issue in a previous version (1.13.2) But you are changing it for some reason.

~~2) You checked yes for `Bug exists on current Vanilla snapshot` so if its a bug in Vanilla why are you reporting it to Spigot?~~

**Comment by md-5** [comment]
As long as its clearly vanilla I dont mind too much, although obviously mojira is the place to post it and more likely to get a fix (unless its a serious bug)

**Comment by ShaneBeee** [comment]
> As long as its clearly vanilla I dont mind too much, although obviously mojira is the place to post it and more likely to get a fix (unless its a serious bug)

OOPs my apologies ... I thought it was the same rules as Spigot's Jira.
