### ISSUE TITLE
A chunk at or near (-401 / 74 / -127) causes a crash on join

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#445]
I'm not sure what the cause of the crash is but when joining the server at the location (X: -401 Y: 74 Z: -127) the server crashes. When you move from spawn to the location it doesn't cause a crash.

- [ ] Bug exists on current Vanilla snapshot
- [?] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)

**Comment by ghost** [comment]
Seems that the server is no longer crashing at that location. Possibly check crash reports.

**Comment by md-5** [comment]
Pretty much all the crashes were the standard vanilla chunk loading one that is plaguing the server
