### ISSUE TITLE
Paintings don't despawn when breaking the block it's attached to.

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#447]
Place a painting onto a block then destroy the block. Might be a conflict with a plugin.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.14)
- [x] Bug does not exist on current Spigot version (1.13.2)
###

**Comment by md-5** [comment]
In vanilla they do take like 5+ seconds to break, but yes looks like a plugin.

Bets on GriefPrevention...

**Comment by md-5** [comment]
Yeah it is, we may need to look into removing it tbh, seems to alter a fair bit of behaviour
