### ISSUE TITLE
BlastFurnaces and Smoker still accessible even when area is claimed 

### ISSUE THREAD

**Issue by caputoortega** [SpigotMC/SpigotCraft#448]
- [] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [x] Bug does not exist on current Spigot version (1.13.2)

As the title says, players can still interact with the new Blast furnace and Smoker blocks even when the area they're placed is protected by GriefPrevention.

**Comment by MiniDigger** [comment]
That's more like an issue of grief prevention not being updated to support them

**Comment by md-5** [comment]
At a glance the griefprevention code looks ok, but so does the bukkit code...

Do you have the coordinates of a claim @caputoortega ?

**Comment by md-5** [comment]
I can't reproduce

**Comment by caputoortega** [comment]
@md-5
Bug seems to not be reproducible now
Claim coordinates were X: 32 Y: 63 Z -142
I don't know if LogBlock allows you to search through the latest inventory interactions on the blocks like CoreProtect because I never used it, but if it's possible to do that check the latest interactions on the Smoker and Blast Furnace and you'll see I put some wood planks and then removed them.
