### ISSUE TITLE
Light Update Issues

### ISSUE THREAD

**Issue by ShaneBeee** [SpigotMC/SpigotCraft#450]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [x] Bug does not exist on current Spigot version (1.13.2)

I have noticed in my village, the lights are not updating at night time. 
For example, I have lanterns placed around my village, when I log in they are not putting off any light.
If I break the lantern and place it, the light then shows up.

I loaded up a vanilla MC server, and that seems to work totally fine.

Im trying to log in right now to take some pictures but the server keeps crashing. Im starting to wonder if this is an issue with the chunk I am at, but I figured I would report this issue in the event anyone else noticed the same behaviour with lights.

**Comment by md-5** [comment]
Can you reproduce it in a new area?

**Comment by ShaneBeee** [comment]
Next time I am able to get onto the server, I will see if I can replicate it in a new area, and if so then I will post pics, if not I will close this.

**Comment by ShaneBeee** [comment]
Did more testing, I think this is just an issue in the chunk I am in. Seems to work totally fine elsewhere in the world.
