### ISSUE TITLE
Furnace items are deleted when using some fuels

### ISSUE THREAD

**Issue by axus** [SpigotMC/SpigotCraft#453]
Tried on play.spigotmc.orb 19w13b

Most things will delete the furnace contents when used as fuel in the furnace.  oak planks and birch planks work, dark oak planks don't, birch logs do but not other kinds of logs.

Also, when the furnace completes the smelting, furnace contents are often deleted.  Things can be removed before the furnace completes.

- [X] Bug does not exist on current Vanilla snapshot
- [X] Bug does not exist on current Spigot version (1.13.2)

**Comment by md-5** [comment]
I THINK this is the same bug as https://github.com/SpigotMC/SpigotCraft/issues/451

Would you mind please testing now that I've fixed that?

Thanks

**Comment by axus** [comment]
Yep I tested the blocks that broke before, furnaces work now for a bunch of things.  I guess it was the changing block type?

**Comment by md-5** [comment]
Yeah, tiles were being wiped by block updates
