### ISSUE TITLE
KeepInventory is not consistent between Overworld and other Dimensions

### ISSUE THREAD

**Issue by SameytheHedgehog** [SpigotMC/SpigotCraft#456]
KeepInventory seems to be disabled in the End and Nether, even if it's active in the Overworld (Oh and you can't manually set it in the End or Nether, it simply doesn't work)

First start the server and enter the world. Then set the gamerule KeepInventory to true. (be sure to be in survival) grab something, and go to the End or Nether, and find a way to die.

You won't spawn with the item you grabbed, however if you die in the Overworld with something in your inventory, it'll be with you when you spawn again.

I have tried this at first on the beta 1.14 branch initally, but it appears to happen on the current version also.
---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [X] Bug exists on current Spigot version (1.13.2)
- [ ] Bug does not exist on current Spigot version (1.13.2)

- [X] Bug exists on Beta Spigot version (1.14)

**Comment by md-5** [comment]
1) This is not a bug tracker for release
2) The issue you describe was already fixed - https://hub.spigotmc.org/jira/browse/SPIGOT-4790 - you are probably outdated
