### ISSUE TITLE
WhiteList 1.14.2

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#457]
Hi.
I make a 1.14.2 spigot server and its whitelisted but whitelist command in console not work

>whitelist
[15:20:09] [Server thread/INFO]: Unknown command
[15:20:09] [Server thread/INFO]: /whitelist<--[HERE]

**Comment by yannicklamprecht** [comment]
That's the wrong place to ask.
You forgot to add parameters.
Valid ones are
list
add _<Playername>_
remove _<Playername>_
on
off
