### ISSUE TITLE
1.14.4 Villagers not going through Nether portals

### ISSUE THREAD

**Issue by 1mario999** [SpigotMC/SpigotCraft#459]
1.14.4  i can't get any villagers on my spigot server to go through 
i switched to a vanilla jar and villagers can go through

Bug does not exist on current Vanilla snapshot
Bug exists on current Spigot version (1.14.4)

**Comment by Black-Hole** [comment]
This bug tracker is for the Spigot test server.
For issue with the Spigot server software, please use the bug tracker at https://hub.spigotmc.org/jira
Please read the guideline there carefully and provide more details if you create an issue there.
