### ISSUE TITLE
Placing Blocks Does Incorrect Double Place Animation

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#460]
I feel like this could be a latency based vanilla issue, or due to plugins. Cannot reproduce on local test server, need to test vanilla.

**Comment by md-5** [comment]
Yeah this is in Vanilla - its really bad. Must be latency based as can only reproduce on remote servers.
Is there an MC bug report for it?

**Comment by MrSpock78** [comment]
I found this report:
https://bugs.mojang.com/browse/MC-163910

**Comment by md-5** [comment]
Thanks very much

**Comment by ShaneBeee** [comment]
I think it is latency based. I couldn't replicate this on the server, but after the TPS dropped and some lag happened, I then started to notice this happening. 


> I found this report:
> https://bugs.mojang.com/browse/MC-163910

I was literally JUST About to post that haha, I've been searching for a few minutes.
