### ISSUE TITLE
Use of the anvil crashes the game

### ISSUE THREAD

**Issue by MiniDigger** [SpigotMC/SpigotCraft#464]
opening an anvil and placing an item crashes the client with a stackoverlow: https://paste.md-5.net/ehukukodog.php
https://streamable.com/hjiwb

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [x] Bug does not exist on current Spigot version (1.13.2)

**Comment by md-5** [comment]
Dupe
https://github.com/SpigotMC/SpigotCraft/issues/463
