### ISSUE TITLE
Weird ghast behaviour

### ISSUE THREAD

**Issue by MrIvanPlays** [SpigotMC/SpigotCraft#469]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [x] Bug does not exist on current Spigot version (1.14.4)

When you move nearby to a ghast, the ghast disappears. When you move out after a certain amount of time you will start hearing it again.

**Comment by md-5** [comment]
The ghast disappears or its sound does?

**Comment by md-5** [comment]
I can't reproduce anything 'weird'
