### ISSUE TITLE
Can't place saplings on dirt/grass if block below is air

### ISSUE THREAD

**Issue by MrSpock78** [SpigotMC/SpigotCraft#470]
- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

Can't place saplings on dirt/grass if block below is air.
Tested in creative- and survival mode.
Spigot testserver 1.15 Pre6
![Screenshot_1](https://user-images.githubusercontent.com/28217121/70366759-08ce7600-189a-11ea-8822-d8fddc15437c.png)

Vanilla 1.15 Pre6
![Screenshot_2](https://user-images.githubusercontent.com/28217121/70366856-f6087100-189a-11ea-9086-39bed08bebf5.png)

**Comment by md-5** [comment]
Not sure how/why but I think its a plugin since my empty test server  works fine
