### ISSUE TITLE
Switching to vanilla resets nether

### ISSUE THREAD

**Issue by 5HT2** [SpigotMC/SpigotCraft#476]
SpigotCraft Issue Template
==========================
---

Not 100% sure how to fill this out due to the nature of the bug 

- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.15.2)
- [ ] Bug does not exist on current Spigot version (1.15.2)

To reproduce:

- generate some nether chunks and do something in them on vanilla

- upgrade to spigot

- downgrade to vanilla

- any changes made while on spigot are gone

**Comment by MiniDigger** [comment]
This is not the place to report spigot bugs, use jira.

Generally, vanilla and spigot have slightly different world formats, vanilla stores them as a dimension while in bukkit they are a seperate worlds. You might have to move the world back to the dimension folder if you want to downgrade.

**Comment by 5HT2** [comment]
Oh, I see. Thank you!
