### ISSUE TITLE
Internal Server Error while joining

### ISSUE THREAD

**Issue by d-513** [SpigotMC/SpigotCraft#477]
Didn't check in vanilla snapshot as I don't know where I logged out and stuff, but baisicly when joining SpigotCraft i get this error: "Internal server error". My friend can join, but I can't.

![screenshot](https://i.imgur.com/9X8Pdbs.png)

**Comment by MiniDigger** [comment]
Can you start MC with the console open, so you can see the client error?

Might also help to send the exact timestamp you tried to join to md can take a peek at the logs

**Comment by d-513** [comment]
> Can you start MC with the console open, so you can see the client error?
> 
> Might also help to send the exact timestamp you tried to join to md can take a peek at the logs

Not sure if I did it correctly, but here is my minecraft output when I try to join: https://hastebin.com/ovamakohas.makefile (happens every time I try to join).  Seems werid that there are no errors in the console, but I still can't join.

**Comment by MiniDigger** [comment]
your timezone is UTC+1?
when md has time he can take at the logs at 11:25:20.638 UTC+1 and will see whats wrong. Most likely its something to do with your profile, whats your minecraft username?

**Comment by d-513** [comment]
> your timezone is UTC+1?
> when md has time he can take at the logs at 11:25:20.638 UTC+1 and will see whats wrong. Most likely its something to do with your profile, whats your minecraft username?

My username is dada513, yes it’s utc+1.

**Comment by md-5** [comment]
Yeah I think it happens to anyone that joined pre-20w12a

**Comment by md-5** [comment]
Should be fixed now, please let me know

**Comment by d-513** [comment]
> Should be fixed now, please let me know

Yes, fixed. Thank you md.
