### ISSUE TITLE
publicly available updating process

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [SpigotMC/SpigotCraft#478]
Public update process has many advantages just like open source software. Some warnings can be put in place to inform developers that the API is unstable.  The server administrators may won't notice the warning message, so one can create a file like eula.txt for the server administrator to sign.

**Comment by MiniDigger** [comment]
I mcpconfig likes approach (heres the tools, code are the docs, dont yell at me if you use it wrong) would be cool here

**Comment by md-5** [comment]
I've been through a lot of reasons previously why this isn't the better approach

**Comment by Heath123** [comment]
What reasons specifically?
