### ISSUE TITLE
world - doTick & Task: Tasks & tickEntities. With 48Users

### ISSUE THREAD

**Issue by colo13verdadeo** [SpigotMC/SpigotCraft#479]
Timings:
https://timings.spigotmc.org/?url=muraqiduro
&
https://timings.spigotmc.org/?url=qokiliviyi
&
https://timings.spigotmc.org/?url=muraqiduro

Plugin list:
https://imgur.com/a/8EtzLXD

bukkit.yml, spigot.yml, paper.yml, server.properties
Gist/pastebin/hastebin links

Is server SPIGOT

spigot
This is a final build for 1.12.2. Please see(...)

**Comment by 2008Choco** [comment]
1. 1.12.2 is not a supported version of Bukkit
2. This is the issue tracker for Spigot's test server. Questions regarding issues to do with _your_ server should be taken to the Spigot forums under the [Spigot Help forum](https://www.spigotmc.org/forums/spigot-help.40/).
