### ISSUE TITLE
Respawn Anchor Explosion Not Replicated To Server

### ISSUE THREAD

**Issue by ryanhaticus** [SpigotMC/SpigotCraft#484]
On 1.16, the respawn anchor BLOCK explosion isn't replicated on the server. However, it will kill mobs and the actual block will destroy itself. You can only see block damage on the client and rejoining will restore the blocks.

**This bug is only present in the Overworld. The end works as expected.**

- [] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

**Comment by 2008Choco** [comment]
Can confirm. Creates ghost blocks around the respawn anchor when it explodes. Does not happen on vanilla.

**EDIT:** Might this be as a result of WorldGuard preventing explosions from happening (as was the case on the 1.15 test server)?

**Comment by md-5** [comment]
Yeah.... its kind of mojangs fault though, they forgot a `!isClient` check. Winding back all the client prediction isnt super easy (mainly also because of the fire)

**Comment by md-5** [comment]
https://bugs.mojang.com/browse/MC-177462

**Comment by EazyFTW** [comment]
This can be closed. Fixed on MC's side.
