### ISSUE TITLE
Respawn Anchor not working 

### ISSUE THREAD

**Issue by LegameMc** [SpigotMC/SpigotCraft#485]
Dying in nether doesn't respawn at Respawn Anchor ( Respawn Anchor is activated )

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [x] Bug does not exist on current Spigot version (1.14.4)

**Comment by md-5** [comment]
I assume this is eg essentials home overriding
