### ISSUE TITLE
/locate Bastion_Remnants throws internal error

### ISSUE THREAD

**Issue by 2008Choco** [SpigotMC/SpigotCraft#490]
Executing `/locate Bastion_Remnants` seems to throw an exception (which is not visible as we do not have access to the console). This is not the case for other structures.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [x] Bug does not exist on current Spigot version (1.14.4)

**Comment by md-5** [comment]
Fixed
