### ISSUE TITLE
Breaking Furnace Crashes Server

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#491]
- Was not able to reproduce on Vanillacord 20w17a, only on SpigotCraft 20w17a.
- To reproduce, break an normal furnace.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.15.2)
- [x] Bug does not exist on current Spigot version (1.15.2)

**Comment by klugemonkey** [comment]
When server restarts, block where furnace was is empty, void of lighting and there is no furnace in player inventory.

**Comment by md-5** [comment]
Fix going out now

**Comment by klugemonkey** [comment]
Looks fixed.
