### ISSUE TITLE
List and Link Plugins in README

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#493]
It would be great if the plugins are listed with the link to their resource page in the README. Some plugins have similar names to other plugins, I am having finding their respective resource pages when this happens.

**Comment by 2008Choco** [comment]
You're welcome to make this change yourself. Pull requests are available. Fork, clone (or even just edit the README on GitHub) and pull request

**Comment by ghost** [comment]
I would love to but I can't find the resource pages of some of the plugins because there are multiple plugins with the same or similar name.

**Comment by 2008Choco** [comment]
I would create the pull request anyways. If there are any plugins which you're unsure of, note that in the PR stating that clarification is required. At least do what you can confidently identify 😄 If there are any to which you cannot link, @md-5 (or another community member) can let you know
