### ISSUE TITLE
Placing the last block of a stack then clicking on the empty slot gives the item(s) back

### ISSUE THREAD

**Issue by DrakoTrogdor** [SpigotMC/SpigotCraft#494]
Placing the last block of a stack (such as dirt, granite or even gold ore in my case), and then clicking on the empty slot gives a second copy of the items placed (I've done this with both one, two and eight blocks). This allows me to duplicate any type of block that I can place.

I can recreate the issue on the RC1 server even after re-logging.

---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

**Comment by md-5** [comment]
Confirmed

**Comment by md-5** [comment]
Update going out now
