### ISSUE TITLE
See bubbles through the glass

### ISSUE THREAD

**Issue by Blueeyestar** [SpigotMC/SpigotCraft#495]
in the latest server version from 1.16 you can unfortunately not see any bubbles through the glass. this was possible in the snaphots from 1.16. Please fix if possible

Pre-release bubbles available

![blasen](https://user-images.githubusercontent.com/35557302/85214919-f9b0a080-b371-11ea-87a6-9d177b61aced.png)

bubbles are not visible in the current version

![blasen2](https://user-images.githubusercontent.com/35557302/85214930-0b924380-b372-11ea-9a56-e236d843d996.png)

**Comment by Blueeyestar** [comment]
I also reported this as the current bug if spigot does not make the mistake

https://bugs.mojang.com/projects/MC/issues/MC-190793?filter=allopenissues

**Comment by md-5** [comment]
You need to enable fabulous graphics in the settings
