### ISSUE TITLE
Doors do not open with redstone signal

### ISSUE THREAD

**Issue by DrakoTrogdor** [SpigotMC/SpigotCraft#496]
Both Iron and Oak doors do not respond to redstone signals from either levers, buttons or pressure plates.

Tried both inside claimed area and outside claimed area.
---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

**Comment by md-5** [comment]
I hate redstone, but fix prepared

**Comment by DrakoTrogdor** [comment]
Yay, thank you! Tested and working!
