### ISSUE TITLE
Overworld animals spawn in the nether in the air

### ISSUE THREAD

**Issue by Blueeyestar** [SpigotMC/SpigotCraft#497]
In the latest 1.16-rc1 spawn animals and mobs in the nether. Even in the air.

![2020-06-21_13 51 15](https://user-images.githubusercontent.com/35557302/85223908-bb919c00-b3c6-11ea-84c7-753521867e42.png)
![2020-06-21_13 50 56](https://user-images.githubusercontent.com/35557302/85223910-bcc2c900-b3c6-11ea-89dd-af69c805201c.png)

**Comment by Blueeyestar** [comment]
or is the map broken? us you should generate a new server? because suddenly the upper world comes in the Nether

![2020-06-21_13 59 41](https://user-images.githubusercontent.com/35557302/85224019-a0735c00-b3c7-11ea-860c-b188f92b4fd1.png)

**Comment by md-5** [comment]
Yeah nether and end are cooked and will have to be reset once bug fixed
