### ISSUE TITLE
Lava doesn't flow

### ISSUE THREAD

**Issue by Blueeyestar** [SpigotMC/SpigotCraft#501]
In the latest 1.16-rc1 No lava flows in the nether. 

![2020-06-22_15 34 05](https://user-images.githubusercontent.com/35557302/85293861-37124c80-b49e-11ea-9916-84f8b223c35e.png)

in the Vanilla Singleplay 1.16-rc1 the lava runs normally as usual

**Comment by md-5** [comment]
Confirmed
