### ISSUE TITLE
Wither Skeletons do not track or attack players/mobs, they do path find.

### ISSUE THREAD

**Issue by DrakoTrogdor** [SpigotMC/SpigotCraft#502]
Wither Skeletons do not track or attack players/mobs, although they do path-find.
Even after being attacked they do not reciprocate, they just continue on their happy little path-finding adventures

---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

**Comment by Blueeyestar** [comment]
Spigot-Vers.1.16-rc1 
I can confirm. They are not aggressive against players

in the Vanilla Singleplay 1.16-rc1 they behave naturally and attack players

**Comment by md-5** [comment]
They work in overworld but not the nether

**Comment by md-5** [comment]
Same as #501
