### ISSUE TITLE
Curing a Zombie Villager is instantaneous and causes them to lose their profession.

### ISSUE THREAD

**Issue by DrakoTrogdor** [SpigotMC/SpigotCraft#503]
Curing a Zombie Villager is instantaneous and causes them to lose their profession.
I have tested this twice on the server.
---

- [ ] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [ ] Bug does not exist on current Spigot version (1.14.4)

**Comment by md-5** [comment]
Hmm its not instant for me

**Comment by DrakoTrogdor** [comment]
Found a wild zombie villager in a ravine cavern and it still converted instantly.

**Comment by md-5** [comment]
How do you get a zombie villager normally?
I'm using spawn eggs, but is there a way to convert an existing villager to zombie?

**Comment by DrakoTrogdor** [comment]
I've just been capturing zombie villagers that I find in caves (sometimes easier than transporting two villagers a long distance).  I think that might be the difference.

**Comment by md-5** [comment]
Thanks, I'll try that

**Comment by md-5** [comment]
Confirmed for natural zombies

**Comment by md-5** [comment]
I actually think this is an existing bug in 1.15 also, the instant convert at least
