### ISSUE TITLE
Client is not informed of explosion in The End

### ISSUE THREAD

**Issue by 2008Choco** [SpigotMC/SpigotCraft#505]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [x] Bug does not exist on current Spigot version (1.14.4)

The client is not informed of explosions in The End. This includes end crystals and tnt. The explosion still occurs and damage is still inflicted on the player, though no blocks are destroyed and no explosion sound nor particles are displayed to the client. I cannot replicate this in The Nether nor The Overworld. I presume GriefPrevention is at fault but figured this was worth mentioning as it makes the Ender Dragon fight much more difficult. The Dragon is not damaged by the crystals exploding.

**Comment by 2008Choco** [comment]
Possibly related to #502

**Comment by md-5** [comment]
Same as #501
