### ISSUE TITLE
Vein-Miner doesn't work with Netherite Tools

### ISSUE THREAD

**Issue by DrakoTrogdor** [SpigotMC/SpigotCraft#506]
Not sure if this should be reported here in order to edit the Vein Miner config, or if the Vein Miner plugin creator should be notified.

Vein-Miner doesn't work with Netherite Tools
---

- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [X] Bug does not exist on current Spigot version (1.14.4)

**Comment by DrakoTrogdor** [comment]
Issue has been fixed on Vein-Miner repo.

**Comment by 2008Choco** [comment]
Worth noting that this just requires a configuration change 😄
