### ISSUE TITLE
how do I set the package destination maven?

### ISSUE THREAD

**Issue by AntonCrasher** [SpigotMC/SpigotCraft#517]
how do I change the maven package destination like here?

`[INFO] `
`[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Manhunt ---`
`[INFO] Building jar: C:\Users\Anton\IdeaProjects\Manhunt by Antoha\target\Manhunt-1.0-SNAPSHOT.jar`

i tried doing this: 

```
<resources>
      <resource>
            <directory>C:\Users\Anton\Desktop\PluginForMinecraft\Server\plugins</directory>
      </resource>
</resources>
```

i want to change the building jar destination. Anyone knows how? Thanks.

note: I am new to making good posts on github please give comments to my posts if something is bad

**Comment by lokka30** [comment]
this is the issues section for the SpigotCraft server, not for getting help for programming your resources. that's what the forums and discord server are for :)

**Comment by AntonCrasher** [comment]
then where do i post this

**Comment by lokka30** [comment]
SpigotMC's 'plugin development' forum or the help chat in SpigotMC's Discord server. :)
