### ISSUE TITLE
Item visually disappear in crafting table

### ISSUE THREAD

**Issue by nahkd123** [SpigotMC/SpigotCraft#519]
The item just visually disappear in crafting table.
Demonstration: https://user-images.githubusercontent.com/20136708/117300305-9ead6c80-aea3-11eb-9557-4cf3a43a753d.mp4

---

- [x] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.16.5)
- [x] Bug does not exist on current Spigot version (1.16.5)

**Comment by md-5** [comment]
Should be fixed

**Comment by nahkd123** [comment]
Confirmed that this issue is solved.
