### ISSUE TITLE
21w19a - Text disappears on Sign placement

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#521]
21w19a - Text disappears on Sign placement
==========================

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.16.4)
- [x] Bug does not exist on current Spigot version (1.16.4)

**Comment by md-5** [comment]
Should be fixed now

**Comment by ghost** [comment]
Issue is fixed.
