### ISSUE TITLE
21w19a - Kicked for "Internal Server Error" when freezing

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#523]
21w19a - Kicked for "Internal Server Error" when freezing
==========================

Place Powder Snow using a Powder Snow Bucket then walk into the Powder Snow whilst in survival mode and wait in it until you receive freezing hearts.

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.16.4)
- [x] Bug does not exist on current Spigot version (1.16.4)

**Comment by ghost** [comment]
Also, a server crash occurs when a mob freezes in Powder Snow.

**Comment by md-5** [comment]
Should hopefully be fixed

**Comment by ghost** [comment]
Issue is fixed.
