### ISSUE TITLE
21w19a - Activated Dispenser with a Powder Snow Bucket causes server to crash

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#524]
21w19a - Activated Dispenser with a Powder Snow Bucket causes server to crash
==========================

Place a Dispenser putting a Powder Snow Bucket into it and activate the Dispenser so the Powder Snow is placed then activate it again to retrieve the Powder Snow into the empty Bucket.

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.16.4)
- [x] Bug does not exist on current Spigot version (1.16.4)

**Comment by md-5** [comment]
Should be fixed now

**Comment by ghost** [comment]
The crash still occurs for this issue.

**Comment by md-5** [comment]
OK this should really be fixed now

**Comment by ghost** [comment]
Issue is fixed.
