### ISSUE TITLE
21w19a - Cauldron not filling with Lava when using a Lava Bucket

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#525]
21w19a - Cauldron not filling with Lava when using a Lava Bucket
==========================

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.16.4)
- [x] Bug does not exist on current Spigot version (1.16.4)

**Comment by md-5** [comment]
Thanks for the comprehensive testing of these bugs, let me know if there's anything we can do to help

**Comment by md-5** [comment]
Should be fixed now

**Comment by ghost** [comment]
Issue is fixed.
