### ISSUE TITLE
Server is down but free IP address :D 

### ISSUE THREAD

**Issue by BassyBoo55** [SpigotMC/SpigotCraft#532]
![image](https://user-images.githubusercontent.com/80031375/160884194-7ae63b10-6d55-4342-aaa0-264c21385f77.png)

**Comment by olijeffers0n** [comment]
This is not exactly a security concern, the IP is basically public and can be obtained through a simple lookup

**Comment by outsparkled** [comment]
traceroute/tracert does the exact same thing, the ip is not secret.
https://man7.org/linux/man-pages/man8/traceroute.8.html

**Comment by BassyBoo55** [comment]
The server is down that was the main thing lol
