### ISSUE TITLE
1.19-pre3 - Entity positions aren't being sent to the player

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#541]
Entities appear "laggy" and can be in a different location to the player.

https://youtu.be/qlVuZ7TMiak

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.19-pre3)
- [ ] Bug does not exist on current Spigot version (1.19-pre3)

**Comment by md-5** [comment]
Should now be resolved
