### ISSUE TITLE
1.19-pre3 - Opening the inventory on a Boat with Chest causes server to crash

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#543]
Opening the inventory on a Boat with Chest causes server to crash. This can be shift+right-clicking the chest or right-click when an entity is already a passenger.

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.19-pre3)
- [ ] Bug does not exist on current Spigot version (1.19-pre3)

**Comment by md-5** [comment]
Should now be resolved
