### ISSUE TITLE
1.19-pre3 - Being in a chunk with a Frog causes the server to crash

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#545]
Being in a chunk with a Frog causes the server to crash.

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.19-pre3)
- [ ] Bug does not exist on current Spigot version (1.19-pre3)

**Comment by md-5** [comment]
Should now be resolved
