### ISSUE TITLE
1.19-pre3 - Mangrove Propagule don't grow when using Bone Meal

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#546]
Mangrove Propagule don't grow when using Bone Meal.

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.19-pre3)
- [ ] Bug does not exist on current Spigot version (1.19-pre3)

**Comment by md-5** [comment]
Should now be resolved
