### ISSUE TITLE
1.19-pre3 - Stuck on "Loading terrain..." after disconnecting on respawn screen

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#548]
If you disconnect from the server on the respawn screen, then reconnect, if the chunk is unloaded that you died in, your client gets stuck on the "Loading terrain..." screen.

https://youtu.be/xXf-G6vu2zM

I created the same issue for 1.18.2:
https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-7009

---

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [x] Bug exists on current Spigot version (1.19-pre3)
- [ ] Bug does not exist on current Spigot version (1.19-pre3)

**Comment by md-5** [comment]
This should be fixed now
