### ISSUE TITLE
Towny instead of GriefPrevention

### ISSUE THREAD

**Issue by picknchew** [SpigotMC/SpigotCraft#55]
It just kind of brings the community in areas instead of random claims everywhere.

**Comment by RoboMWM** [comment]
Towny has numerous defaults (iirc, like no building in the wilderness), and it's complicated to figure out for claiming land (you have to be a mayor or something and can only have so much until you have more people in a town or money or something), especially for the lifespan of this server (used for testing the snapshot). :-1:

**Comment by picknchew** [comment]
Permission to build in the wilderness can be given to players. There could be several default towns with free plots for players to claim. Towns can be made with unlimited claiming power.

**Comment by RoboMWM** [comment]
What if someone wants to claim land somewhere in the wilderness and not be required to be restricted to a pre-determined plot?

**Comment by Cldfire** [comment]
:-1:

Towny is not the land-claiming solution we're looking for.

**Comment by AlexM850** [comment]
Definitely not Towny, but i don't think Grief prevention either.

**Comment by HeroCC** [comment]
:-1:

**Comment by ghost** [comment]
:-1:

Like @RoboMWM and @Cldfire said.

**Comment by DoNotSpamPls** [comment]
:-1:

**Comment by incognitojam** [comment]
:-1:

**Comment by TomLewis** [comment]
:-1:
