### ISSUE TITLE
SpigotCraft Disucssion 

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#64]
I think you should add a SpigotCraft discussion section to the forums. It could possibly be a sub forum to the current Spigot Server section or you could sticky the current threads in it and allow us to post in it.

**Comment by RoboMWM** [comment]
There is https://www.spigotmc.org/forums/spigot-server.81/

**Comment by ghost** [comment]
@RoboMWM But only @md-5 can post there. Like I said at the end, sticky the current threads in it and allow us to post in it.

**Comment by ghost** [comment]
@RoboMWM Sorry if I wasn't clear.

**Comment by RoboMWM** [comment]
I read too quickly again but either way I'm sure he'll add a new section if it's needed. This is mostly for testing anyways (idk how they discussed stuff last year, was out of the MC scene back then).

**Comment by ghost** [comment]
@RoboMWM: https://www.spigotmc.org/threads/1-8-testing-begins.34636/

**Comment by csh** [comment]
It'd be neat if we could get something like a gitter set up for this.

**Comment by ctian1** [comment]
We have an IRC channel at irc.spi.gt, #spigot-server

**Comment by csh** [comment]
Oh yeah! Totally forgot you guys have an IRC :P
