### ISSUE TITLE
Problem with plots

### ISSUE THREAD

**Issue by dyanakiev** [SpigotMC/SpigotCraft#69]
I get like bad chunks ;D i have no idea why.. this is on clean server

http://i.imgur.com/ZujGLaT.png

When i relogin is ok but when after few seconds bug is here.

**Comment by RoboMWM** [comment]
Either a client issue or more likely, the plot isn't claimed. Only plots that are claimed are rendered due to PlotSquared's dynamic border - this is to prevent server load from generating unneeded chunks.

**Comment by TheEVIL** [comment]
this plot is claimed..
