### ISSUE TITLE
BuildAPrefix

### ISSUE THREAD

**Issue by meyerzinn** [SpigotMC/SpigotCraft#70]
Disclosure: I made this plugin.

If we add BAP we'd have a good self-service prefix plugin. Just sayin'.

**Comment by ctian1** [comment]
... link please

Sounds unnecessary anyways

**Comment by meyerzinn** [comment]
Oh, is this just bare necesseties? (Not the song.)

**Comment by TomLewis** [comment]
:thumbsdown:

**Comment by ctian1** [comment]
:-1:
