### ISSUE TITLE
Fire spread

### ISSUE THREAD

**Issue by picknchew** [SpigotMC/SpigotCraft#78]
Fire spread is off meaning that the nether inaccessible. Is this intended?

**Comment by RoboMWM** [comment]
Fire spread is disabled by default in GP, however I don't think nether portals need firespread... Will toggle those options in a PR though since firespread inside claims is always disabled.

Update: See #79

**Comment by picknchew** [comment]
Fire does not appear in and outside claims meaning that nether portals will not work. I've tried inside of a claim. But fire instantly disappears both inside and outside.

**Comment by RoboMWM** [comment]
Fire itself isn't blocked. If that's the case, someone might've disabled fire (lighting) completely in WorldGuard. Will take a look.
