### ISSUE TITLE
Able to place lava in a claim

### ISSUE THREAD

**Issue by picknchew** [SpigotMC/SpigotCraft#83]
I was able to place lava in someone else's claim. Taking it back however, dupes the lava meaning the lava stays on the ground and lava is placed in my bucket.

**Comment by konsolas** [comment]
http://i.imgur.com/x1OjAYo.jpg

He did this

RIP crops

**Comment by RoboMWM** [comment]
Did you use the off hand to do this? I don't know if any events fire for that.

**Comment by picknchew** [comment]
No, with just my right hand

**Comment by RoboMWM** [comment]
Well, I do know events for buckets are separate from interact events, though not sure if anything changed on that front. Though in chat you stated you were spamming it?

**Comment by picknchew** [comment]
That's how I discovered it yes, but it works even without spamming

**Comment by RoboMWM** [comment]
I wasn't able to reproduce on spigot 1.8.8, so perhaps something in the API changed :s

**Comment by md-5** [comment]
Fix made for next update
