### ISSUE TITLE
Boats kick for flying when in them.

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#85]
I placed a boat and tried to ride in it (several times). Each time I was kicked for flying.

**Comment by RoboMWM** [comment]
If you can tell us the exact message you are kicked with that'd be nice (to determine what is kicking you)

**Comment by ghost** [comment]
"Flying is not enabled on this server"

(accidently closed it for a sec)

**Comment by RoboMWM** [comment]
Hmm, that sounds like a vanilla bug, odd.

**Comment by md-5** [comment]
Fix made for next update.

**Comment by TomLewis** [comment]
Was this a setting in nocheatplus?

**Comment by RoboMWM** [comment]
This is not a NCP message.
