### ISSUE TITLE
Baby Zombies not burning

### ISSUE THREAD

**Issue by tim740** [SpigotMC/SpigotCraft#86]
Normal zombies are burning but baby zombies aren't, they don't even have hats on.

**Comment by RoboMWM** [comment]
Normal vanilla behavior.

**Comment by tim740** [comment]
No, they dont burn in the daytime when adults do.

**Comment by RoboMWM** [comment]
Correct, baby zombies do not burn in daylight.

**Comment by tim740** [comment]
Just remembered forget this
