### ISSUE TITLE
Furnace takes 2 coal

### ISSUE THREAD

**Issue by picknchew** [SpigotMC/SpigotCraft#92]
The furnace takes 2 coal for 8 items. One coal should be able to smelt exactly 8 items.

Steps to reproduce:
Place 2 coal in furnace and 8 items of any smelt-able item.

**Comment by tim740** [comment]
I noticed this too

**Comment by picknchew** [comment]
See: http://minecraft.gamepedia.com/Coal#Fuel

**Comment by md-5** [comment]
Cannot reproduce
