### ISSUE TITLE
Replace Essentials with (check desc)

### ISSUE THREAD

**Issue by tim740** [SpigotMC/SpigotCraft#93]
Replace Essentials with:

This Tpa plugin (or one like it): https://www.spigotmc.org/resources/tpa.1807/

This Home plugin (or one like it): http://dev.bukkit.org/bukkit-plugins/bedhome/

To keep the vanilla feel! :D

Remember essentials uses loads of ram

**Comment by tim740** [comment]
For Admin Stats you could use this (or something like it): http://dev.bukkit.org/bukkit-plugins/lagmeter/

**Comment by RoboMWM** [comment]
Essentials should be fine. I'm unsure how you determined that Essentials uses "loads of ram" but if you really want to make changes go ahead and make a PR
 :-1: 

Also see https://github.com/SpigotMC/SpigotCraft/pull/54

**Comment by TomLewis** [comment]
:-1:
