### ISSUE TITLE
Taking damage lets you jump 2 blocks

### ISSUE THREAD

**Issue by picknchew** [SpigotMC/SpigotCraft#94]
Upon taking fall damage, you can jump 2 blocks.

**Comment by RoboMWM** [comment]
What do you mean, you jump 2 blocks high instead of 1? Or you can jump twice in mid-air?

**Comment by picknchew** [comment]
Taking fall damage implies that the player is on the ground. The player is able to jump 2 blocks high immediately after taking fall damage

**Comment by RoboMWM** [comment]
Is it like a normal jump or does it appear to be a rubberband effect... a video might help.

**Comment by picknchew** [comment]
Seems it's only an issue when the server is behind and needs to catch-up.
